"""Build the single-request browser bundle from maintainable core modules."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTS = [
    "security.js", "theme.js", "components.js", "drafts.js", "pwa.js", "layout.js",
    "app-config.js", "ui-theme.js", "export.js", "navigation.js",
]
out = ["// Generated by scripts/build_frontend_core.py — do not edit directly.\n"]
for name in PARTS:
    out.append(f"\n// source: js/core/{name}\n")
    out.append((ROOT / "frontend" / "js" / "core" / name).read_text())
(ROOT / "frontend" / "js" / "core-bundle.js").write_text("".join(out))
