(function(){
let stream=null,facing='environment',source=null,files=[],fileIndex=0,scale=1,cameraZoom=1,panX=0,panY=0,drag=null,captureSource='camera',captureTime=null,inputFormat='image/jpeg',saving=false,lastPreviewUrl='',sessionPreviews=[],previewIndex=-1,previewTouchX=0;
const $=id=>document.getElementById(id),canvas=()=>$('cropCanvas'),ctx=()=>canvas().getContext('2d',{alpha:false});
function ready(){return !$('cameraBtn')?.disabled}function streaming(){return !!(stream&&stream.active)}window.vcmsCameraStreaming=streaming;function stop(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('video').srcObject=null;window.vcmsCameraContextChanged?.()}function show(title){$('capture').classList.add('open');$('capTitle').textContent=title}function fail(s){closeCapture();toast(s)}
window.startCameraStream=async function(){if(streaming())return true;$('startCam')?.classList.add('hidden');$('capCount').textContent='Opening camera…';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:2560},height:{ideal:1920},aspectRatio:{ideal:4/3}},audio:false});$('video').srcObject=stream;await $('video').play().catch(()=>{});$('capCount').textContent='Landscape 4:3 · DPR-ready · auto-save';window.vcmsCameraContextChanged?.();return true}catch(e){stream=null;$('startCam')?.classList.remove('hidden');$('capCount').textContent=e?.name==='NotAllowedError'?'Allow Camera access once to continue':'Tap Start Camera to try again';toast(e?.name==='NotAllowedError'?'Camera permission is controlled by iPhone. Tap Allow once.':'Camera could not start. Tap Start Camera or use Gallery.');return false}};
window.openCamera=async function(auto=false){captureSource='camera';captureTime=new Date();inputFormat='image/jpeg';show('VCMS Camera');$('video').classList.remove('hidden');canvas().classList.add('hidden');$('shutter').classList.remove('hidden');$('flip').classList.remove('hidden');$('cameraZoomBar').classList.remove('hidden');$('previewActions').classList.remove('show');$('cropTools').classList.add('hidden');await startCameraStream();window.vcmsCameraContextChanged?.()};
window.flipCamera=async function(){facing=facing==='environment'?'user':'environment';stop();await openCamera()};
window.takePhoto=async function(){if(saving)return;let v=$('video'),context=window.currentCameraContext();if(!context.project_id||!context.item_of_work_name||!context.activity_name)return toast('Select Site, Item of Work and Activity');if(!v.videoWidth||!streaming())return toast('Camera is still starting');saving=true;$('shutter').disabled=true;$('capCount').textContent='Saving photo…';captureTime=new Date();try{let legacy=Number(window.orientation),screenAngle=Number(screen.orientation?.angle),angle=Number.isFinite(screenAngle)&&screenAngle!==0?screenAngle:Number.isFinite(legacy)?legacy:0,landscapeView=matchMedia('(orientation:landscape)').matches||innerWidth>innerHeight,textRotation=Math.abs(angle%180)===90?(angle<0||angle===270?-90:90):(landscapeView?90:0),ratio=4/3,iw=v.videoWidth,ih=v.videoHeight,srcRatio=iw/ih,sx=0,sy=0,sw=iw,sh=ih;if(srcRatio>ratio){sw=ih*ratio;sx=(iw-sw)/2}else{sh=iw/ratio;sy=(ih-sh)/2}let baseW=sw,baseH=sh;sw=baseW/cameraZoom;sh=baseH/cameraZoom;sx+=(baseW-sw)/2;sy+=(baseH-sh)/2;let high=document.createElement('canvas');high.width=Math.min(4032,Math.round(baseW));high.height=Math.round(high.width/ratio);high.getContext('2d',{alpha:false}).drawImage(v,sx,sy,sw,sh,0,0,high.width,high.height);stamp(high,high.getContext('2d',{alpha:false}),textRotation);let small=document.createElement('canvas');small.width=1600;small.height=1200;small.getContext('2d',{alpha:false}).drawImage(high,0,0,small.width,small.height);let q=.88,blob=await blobFrom(small,'image/jpeg',q);while(blob.size>400*1024&&q>.64){q-=.04;blob=await blobFrom(small,'image/jpeg',q)}lastPreviewUrl=URL.createObjectURL(blob);sessionPreviews.push(lastPreviewUrl);if(sessionPreviews.length>20)URL.revokeObjectURL(sessionPreviews.shift());previewIndex=sessionPreviews.length-1;$('lastThumb').src=lastPreviewUrl;$('lastThumb').classList.remove('hidden');$('lastIcon').classList.add('hidden');let id=uuid(),record=queueRecord(blob,id,context,small.width,small.height);await VCMSCameraQueue.enqueue(record);$('capCount').textContent=navigator.onLine?'Saved · uploading in background':'Saved offline · upload pending';toast(navigator.onLine?'Photo saved — ready for next':'Photo saved offline — ready for next');if(navigator.onLine)VCMSCameraQueue.syncOne(id).catch(()=>{}).finally(()=>VCMSCameraQueue.stats().then(s=>window.dispatchEvent(new CustomEvent('vcms-camera-queue',{detail:s}))));}catch(e){toast(e.message||'Could not save photo — try again')}finally{saving=false;window.vcmsCameraContextChanged?.()}};
function showQuick(){if(previewIndex<0||!sessionPreviews.length)return;$('quickImage').src=sessionPreviews[previewIndex];$('quickNumber').textContent=`${previewIndex+1} / ${sessionPreviews.length}`;$('quickPrev').disabled=previewIndex===0;$('quickNext').disabled=previewIndex===sessionPreviews.length-1}window.previewLastPhoto=function(){if(!sessionPreviews.length)return toast('Take a photo first');previewIndex=sessionPreviews.length-1;showQuick();$('quickViewer').classList.add('open')};window.moveQuick=function(step){let next=previewIndex+step;if(next<0||next>=sessionPreviews.length)return;previewIndex=next;showQuick()};window.closeLastPhoto=function(){$('quickViewer').classList.remove('open')};$('quickViewer').addEventListener('touchstart',e=>previewTouchX=e.changedTouches[0].clientX,{passive:true});$('quickViewer').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-previewTouchX;if(Math.abs(dx)>45)moveQuick(dx<0?1:-1)},{passive:true});
window.openGallery=function(){if(ready())$('galleryInput').click()};
$('galleryInput').addEventListener('change',async e=>{files=[...e.target.files];fileIndex=0;if(!files.length)return;show('Crop gallery photo');await loadFile(files[0])});
async function loadFile(file){captureSource='gallery';inputFormat=file.type||file.name.split('.').pop()||'unknown';captureTime=await reliableDate(file);let name=file.name.toLowerCase(),heic=/\.(heic|heif)$/.test(name)||/hei[cf]/i.test(file.type||'');if(!((file.type||'').startsWith('image/')||/\.(heic|heif|jpg|jpeg|png)$/.test(name)))return fail('Unsupported image format');try{let input=file,url=URL.createObjectURL(input),im=new Image();try{await new Promise((ok,no)=>{im.onload=ok;im.onerror=no;im.src=url})}catch(nativeError){URL.revokeObjectURL(url);if(!heic||typeof heic2any!=='function')throw nativeError;let converted=await heic2any({blob:file,toType:'image/jpeg',quality:.95});input=Array.isArray(converted)?converted[0]:converted;url=URL.createObjectURL(input);im=new Image();await new Promise((ok,no)=>{im.onload=ok;im.onerror=no;im.src=url})}URL.revokeObjectURL(url);source=im;beginCrop('gallery')}catch(e){fail(heic?'The HEIC photo could not be decoded. Keep the original and try again.':'The selected photo could not be opened.')}}
async function reliableDate(file){if(!/jpe?g/i.test(file.type+file.name))return null;try{let b=await file.slice(0,256*1024).arrayBuffer(),v=new DataView(b);if(v.getUint16(0)!==0xffd8)return null;let o=2;while(o+4<v.byteLength){let marker=v.getUint16(o),len=v.getUint16(o+2);if(marker===0xffe1&&String.fromCharCode(...new Uint8Array(b,o+4,4))==='Exif'){let t=o+10,le=v.getUint16(t)===0x4949,get16=x=>v.getUint16(x,le),get32=x=>v.getUint32(x,le),ifd=t+get32(t+4),n=get16(ifd),exif=0;for(let i=0;i<n;i++){let p=ifd+2+i*12;if(get16(p)===0x8769)exif=t+get32(p+8)}if(exif){let en=get16(exif);for(let i=0;i<en;i++){let p=exif+2+i*12;if(get16(p)===0x9003){let q=t+get32(p+8),s='';for(let k=0;k<19;k++)s+=String.fromCharCode(v.getUint8(q+k));let m=s.match(/(\d{4}):(\d{2}):(\d{2}) (\d{2}):(\d{2}):(\d{2})/);if(m)return new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6])}}}break}o+=2+len}}catch{}return null}
function beginCrop(kind){$('video').classList.add('hidden');canvas().classList.remove('hidden');$('shutter').classList.add('hidden');$('flip').classList.add('hidden');$('cameraZoomBar').classList.add('hidden');$('cropTools').classList.remove('hidden');$('previewActions').classList.add('show');$('capTitle').textContent=kind==='camera'?'Preview photo':'Crop gallery photo';$('capCount').textContent=(files.length?`${fileIndex+1} of ${files.length} · `:'')+(captureTime?'Original time found':'Capture time unavailable');scale=1;panX=0;panY=0;$('zoom').value=1;let [iw,ih]=dims(),cropW=Math.min(iw,ih*4/3),outW=Math.max(1200,Math.min(4032,Math.round(cropW)));canvas().width=outW;canvas().height=Math.round(outW*.75);draw()}
function dims(){return source instanceof HTMLCanvasElement?[source.width,source.height]:[source.naturalWidth,source.naturalHeight]}
function stamp(c,x,rotation=0){let w=c.width,h=c.height;if(rotation===90){x.save();x.translate(w,0);x.rotate(Math.PI/2);drawStamp(x,h,w);x.restore()}else if(rotation===-90){x.save();x.translate(0,h);x.rotate(-Math.PI/2);drawStamp(x,h,w);x.restore()}else drawStamp(x,w,h)}
function drawStamp(x,w,h){let p=Math.max(18,Math.round(w*.025)),line=Math.max(30,Math.round(w*.035)),context=window.currentCameraContext(),paint=(text,y,font)=>{x.font=font;x.fillStyle='#000';x.fillText(text,p,y,w-p*2)};x.save();x.textBaseline='middle';paint(context.item_of_work_name.toUpperCase(),h-line*2.55,`700 ${Math.round(line*.58)}px Arial`);paint(context.activity_name.toUpperCase(),h-line*1.65,`600 ${Math.round(line*.52)}px Arial`);paint(captureTime?formatStamp(captureTime):'CAPTURE TIME UNKNOWN',h-line*.72,`500 ${Math.round(line*.46)}px Arial`);x.restore()}
function formatStamp(d){let mon=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],h=d.getHours(),ap=h>=12?'PM':'AM';return `${String(d.getDate()).padStart(2,'0')} ${mon[d.getMonth()]} ${d.getFullYear()} | ${String(h%12||12).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} ${ap}`}
function draw(){if(!source)return;let [iw,ih]=dims(),cw=canvas().width,ch=canvas().height,base=Math.max(cw/iw,ch/ih),s=base*scale,dw=iw*s,dh=ih*s,maxX=Math.max(0,(dw-cw)/2),maxY=Math.max(0,(dh-ch)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));ctx().fillStyle='#000';ctx().fillRect(0,0,cw,ch);ctx().drawImage(source,(cw-dw)/2+panX,(ch-dh)/2+panY,dw,dh);stamp(canvas(),ctx())}
$('cameraZoom').addEventListener('input',e=>{cameraZoom=Math.max(1,Math.min(100,+e.target.value||1));$('cameraZoomValue').textContent=`${cameraZoom}×`;$('video').style.transform=`scale(${cameraZoom})`;$('video').style.transformOrigin='center'});$('zoom').addEventListener('input',e=>{scale=+e.target.value;draw()});let frame=$('frame');frame.addEventListener('pointerdown',e=>{if(canvas().classList.contains('hidden'))return;drag={x:e.clientX,y:e.clientY,px:panX,py:panY};frame.setPointerCapture(e.pointerId)});frame.addEventListener('pointermove',e=>{if(!drag)return;let ratio=canvas().width/frame.clientWidth;panX=drag.px+(e.clientX-drag.x)*ratio;panY=drag.py+(e.clientY-drag.y)*ratio;draw()});frame.addEventListener('pointerup',()=>drag=null);
window.retake=function(){if(files.length)loadFile(files[fileIndex]);else{source=null;openCamera()}};
function blobFrom(c,type,q){return new Promise(ok=>c.toBlob(ok,type,q))}async function optimized(){let c=document.createElement('canvas');c.width=1600;c.height=1200;c.getContext('2d').drawImage(canvas(),0,0,1600,1200);let q=.88,b=await blobFrom(c,'image/jpeg',q);while(b.size>400*1024&&q>.64){q-=.04;b=await blobFrom(c,'image/jpeg',q)}return b}
async function phoneCopy(blob,id){let file=new File([blob],`VCMS_${id}.jpg`,{type:'image/jpeg'});if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&navigator.canShare?.({files:[file]})){toast('Choose “Save Image” to keep the high-resolution phone copy.');try{await navigator.share({files:[file],title:'VCMS site photo'})}catch(e){if(e.name!=='AbortError')toast('Phone copy was not saved; cloud upload will continue.')}}else{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{let r=Math.random()*16|0;return(c==='x'?r:r&3|8).toString(16)})}function slug(s){return String(s||'project').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,45)||'project'}
function queueRecord(blob,id,context,width=1600,height=1200){let d=captureTime||new Date(),day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,key=`site-photos/${slug(context.project_name)}/${day.slice(0,4)}/${day.slice(5,7)}/${day}/${id}.jpg`;return{photo_id:id,blob,metadata:{photo_id:id,...context,capture_source:captureSource,captured_at:captureTime?.toISOString()||null,imported_at:captureSource==='gallery'?new Date().toISOString():null,uploaded_at:null,r2_object_key:key,public_url:'',file_size:blob.size,width,height,input_format:inputFormat,output_format:'image/jpeg'}}}
window.acceptCrop=async function(){if(saving)return;saving=true;let saveBtn=$('previewActions').querySelector('.primary'),old=saveBtn.textContent;saveBtn.textContent='Saving…';saveBtn.disabled=true;try{draw();let id=uuid(),high=await blobFrom(canvas(),'image/jpeg',.94),small=await optimized(),context=window.currentCameraContext(),record=queueRecord(small,id,context);await VCMSCameraQueue.enqueue(record);let phonePromise=phoneCopy(high,id);if(navigator.onLine){try{await VCMSCameraQueue.syncOne(id);toast(`Uploaded · ${Math.round(small.size/1024)} KB · 1600×1200`)}catch(e){toast('Cloud unavailable — photo is safely stored in Pending')}}else toast('Offline — photo safely stored in Pending');await Promise.allSettled([phonePromise]);if(files.length&&fileIndex<files.length-1){fileIndex++;await loadFile(files[fileIndex])}else{stop();source=null;$('capture').classList.remove('open');files=[];$('galleryInput').value=''}}catch(e){toast(e.message||'Local save failed — keep this screen open and try again.')}finally{saving=false;saveBtn.textContent=old;saveBtn.disabled=false}};
window.closeCapture=function(){if(saving)return;stop();source=null;$('capture').classList.remove('open')};
})();
