(function(){
let stream=null,facing='environment',source=null,files=[],fileIndex=0,scale=1,panX=0,panY=0,drag=null,captureSource='camera',captureTime=null,inputFormat='image/jpeg',saving=false;
const $=id=>document.getElementById(id),canvas=()=>$('cropCanvas'),ctx=()=>canvas().getContext('2d',{alpha:false});
function ready(){return !$('cameraBtn')?.disabled}function stop(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('video').srcObject=null}function show(title){$('capture').classList.add('open');$('capTitle').textContent=title}function fail(s){closeCapture();toast(s)}
window.openCamera=async function(){if(!ready())return;captureSource='camera';captureTime=new Date();inputFormat='image/jpeg';show('Take photo');$('video').classList.remove('hidden');canvas().classList.add('hidden');$('shutter').classList.remove('hidden');$('flip').classList.remove('hidden');$('previewActions').classList.remove('show');$('cropTools').classList.add('hidden');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:2560},height:{ideal:1920}},audio:false});$('video').srcObject=stream}catch(e){closeCapture();toast(e?.name==='NotAllowedError'?'Camera permission denied. Enable Camera access in browser settings.':'Camera could not open. Use Gallery instead.')}};
window.flipCamera=async function(){facing=facing==='environment'?'user':'environment';stop();await openCamera()};
window.takePhoto=function(){let v=$('video');if(!v.videoWidth)return toast('Camera is still starting');captureTime=new Date();let c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);source=c;stop();beginCrop('camera')};
window.openGallery=function(){if(ready())$('galleryInput').click()};
$('galleryInput').addEventListener('change',async e=>{files=[...e.target.files];fileIndex=0;if(!files.length)return;show('Crop gallery photo');await loadFile(files[0])});
async function loadFile(file){captureSource='gallery';inputFormat=file.type||file.name.split('.').pop()||'unknown';captureTime=await reliableDate(file);let name=file.name.toLowerCase(),heic=/\.(heic|heif)$/.test(name)||/hei[cf]/i.test(file.type||'');if(!((file.type||'').startsWith('image/')||/\.(heic|heif|jpg|jpeg|png)$/.test(name)))return fail('Unsupported image format');try{let input=file,url=URL.createObjectURL(input),im=new Image();try{await new Promise((ok,no)=>{im.onload=ok;im.onerror=no;im.src=url})}catch(nativeError){URL.revokeObjectURL(url);if(!heic||typeof heic2any!=='function')throw nativeError;let converted=await heic2any({blob:file,toType:'image/jpeg',quality:.95});input=Array.isArray(converted)?converted[0]:converted;url=URL.createObjectURL(input);im=new Image();await new Promise((ok,no)=>{im.onload=ok;im.onerror=no;im.src=url})}URL.revokeObjectURL(url);source=im;beginCrop('gallery')}catch(e){fail(heic?'The HEIC photo could not be decoded. Keep the original and try again.':'The selected photo could not be opened.')}}
async function reliableDate(file){if(!/jpe?g/i.test(file.type+file.name))return null;try{let b=await file.slice(0,256*1024).arrayBuffer(),v=new DataView(b);if(v.getUint16(0)!==0xffd8)return null;let o=2;while(o+4<v.byteLength){let marker=v.getUint16(o),len=v.getUint16(o+2);if(marker===0xffe1&&String.fromCharCode(...new Uint8Array(b,o+4,4))==='Exif'){let t=o+10,le=v.getUint16(t)===0x4949,get16=x=>v.getUint16(x,le),get32=x=>v.getUint32(x,le),ifd=t+get32(t+4),n=get16(ifd),exif=0;for(let i=0;i<n;i++){let p=ifd+2+i*12;if(get16(p)===0x8769)exif=t+get32(p+8)}if(exif){let en=get16(exif);for(let i=0;i<en;i++){let p=exif+2+i*12;if(get16(p)===0x9003){let q=t+get32(p+8),s='';for(let k=0;k<19;k++)s+=String.fromCharCode(v.getUint8(q+k));let m=s.match(/(\d{4}):(\d{2}):(\d{2}) (\d{2}):(\d{2}):(\d{2})/);if(m)return new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+m[6])}}}break}o+=2+len}}catch{}return null}
function beginCrop(kind){$('video').classList.add('hidden');canvas().classList.remove('hidden');$('shutter').classList.add('hidden');$('flip').classList.add('hidden');$('cropTools').classList.remove('hidden');$('previewActions').classList.add('show');$('capTitle').textContent=kind==='camera'?'Preview photo':'Crop gallery photo';$('capCount').textContent=(files.length?`${fileIndex+1} of ${files.length} · `:'')+(captureTime?'Original time found':'Capture time unavailable');scale=1;panX=0;panY=0;$('zoom').value=1;let [iw,ih]=dims(),cropW=Math.min(iw,ih*4/3),outW=Math.max(1200,Math.min(4032,Math.round(cropW)));canvas().width=outW;canvas().height=Math.round(outW*.75);draw()}
function dims(){return source instanceof HTMLCanvasElement?[source.width,source.height]:[source.naturalWidth,source.naturalHeight]}
function stamp(c,x){let w=c.width,h=c.height,p=Math.max(18,Math.round(w*.025)),line=Math.max(30,Math.round(w*.035));x.save();x.fillStyle='rgba(0,0,0,.70)';x.fillRect(0,h-line*3.25,w,line*3.25);x.fillStyle='#fff';x.textBaseline='middle';x.font=`700 ${Math.round(line*.58)}px Arial`;let context=window.currentCameraContext();x.fillText(context.item_of_work_name.toUpperCase(),p,h-line*2.55,w-p*2);x.font=`600 ${Math.round(line*.52)}px Arial`;x.fillText(context.activity_name.toUpperCase(),p,h-line*1.65,w-p*2);x.font=`500 ${Math.round(line*.46)}px Arial`;x.fillText(captureTime?formatStamp(captureTime):'CAPTURE TIME UNKNOWN',p,h-line*.72,w-p*2);x.restore()}
function formatStamp(d){let mon=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],h=d.getHours(),ap=h>=12?'PM':'AM';return `${String(d.getDate()).padStart(2,'0')} ${mon[d.getMonth()]} ${d.getFullYear()} | ${String(h%12||12).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')} ${ap}`}
function draw(){if(!source)return;let [iw,ih]=dims(),cw=canvas().width,ch=canvas().height,base=Math.max(cw/iw,ch/ih),s=base*scale,dw=iw*s,dh=ih*s,maxX=Math.max(0,(dw-cw)/2),maxY=Math.max(0,(dh-ch)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));ctx().fillStyle='#000';ctx().fillRect(0,0,cw,ch);ctx().drawImage(source,(cw-dw)/2+panX,(ch-dh)/2+panY,dw,dh);stamp(canvas(),ctx())}
$('zoom').addEventListener('input',e=>{scale=+e.target.value;draw()});let frame=$('frame');frame.addEventListener('pointerdown',e=>{if(canvas().classList.contains('hidden'))return;drag={x:e.clientX,y:e.clientY,px:panX,py:panY};frame.setPointerCapture(e.pointerId)});frame.addEventListener('pointermove',e=>{if(!drag)return;let ratio=canvas().width/frame.clientWidth;panX=drag.px+(e.clientX-drag.x)*ratio;panY=drag.py+(e.clientY-drag.y)*ratio;draw()});frame.addEventListener('pointerup',()=>drag=null);
window.retake=function(){if(files.length)loadFile(files[fileIndex]);else{source=null;openCamera()}};
function blobFrom(c,type,q){return new Promise(ok=>c.toBlob(ok,type,q))}async function optimized(){let c=document.createElement('canvas');c.width=1600;c.height=1200;c.getContext('2d').drawImage(canvas(),0,0,1600,1200);let q=.88,b=await blobFrom(c,'image/jpeg',q);while(b.size>400*1024&&q>.64){q-=.04;b=await blobFrom(c,'image/jpeg',q)}return b}
async function phoneCopy(blob,id){let file=new File([blob],`VCMS_${id}.jpg`,{type:'image/jpeg'});if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&navigator.canShare?.({files:[file]})){toast('Choose “Save Image” to keep the high-resolution phone copy.');try{await navigator.share({files:[file],title:'VCMS site photo'})}catch(e){if(e.name!=='AbortError')toast('Phone copy was not saved; cloud upload will continue.')}}else{let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{let r=Math.random()*16|0;return(c==='x'?r:r&3|8).toString(16)})}function slug(s){return String(s||'project').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').slice(0,45)||'project'}
function queueRecord(blob,id,context){let d=captureTime||new Date(),day=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,key=`site-photos/${slug(context.project_name)}/${day.slice(0,4)}/${day.slice(5,7)}/${day}/${id}.jpg`;return{photo_id:id,blob,metadata:{photo_id:id,...context,capture_source:captureSource,captured_at:captureTime?.toISOString()||null,imported_at:captureSource==='gallery'?new Date().toISOString():null,uploaded_at:null,r2_object_key:key,public_url:'',file_size:blob.size,width:1600,height:1200,input_format:inputFormat,output_format:'image/jpeg'}}}
window.acceptCrop=async function(){if(saving)return;saving=true;let saveBtn=$('previewActions').querySelector('.primary'),old=saveBtn.textContent;saveBtn.textContent='Saving…';saveBtn.disabled=true;try{draw();let id=uuid(),high=await blobFrom(canvas(),'image/jpeg',.94),small=await optimized(),context=window.currentCameraContext(),record=queueRecord(small,id,context);await VCMSCameraQueue.enqueue(record);let phonePromise=phoneCopy(high,id);if(navigator.onLine){try{await VCMSCameraQueue.syncOne(id);toast(`Uploaded · ${Math.round(small.size/1024)} KB · 1600×1200`)}catch(e){toast('Cloud unavailable — photo is safely stored in Pending')}}else toast('Offline — photo safely stored in Pending');await Promise.allSettled([phonePromise]);if(files.length&&fileIndex<files.length-1){fileIndex++;await loadFile(files[fileIndex])}else{stop();source=null;$('capture').classList.remove('open');files=[];$('galleryInput').value=''}}catch(e){toast(e.message||'Local save failed — keep this screen open and try again.')}finally{saving=false;saveBtn.textContent=old;saveBtn.disabled=false}};
window.closeCapture=function(){if(saving)return;stop();source=null;$('capture').classList.remove('open')};
})();
