(function(){
const DB='vcms-camera-v1',STORE='photos';let dbp=null,syncing=false;
function db(){if(!dbp)dbp=new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains(STORE)){let s=d.createObjectStore(STORE,{keyPath:'photo_id'});s.createIndex('status','status');s.createIndex('created_at','created_at')}};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return dbp}
async function tx(mode,fn){let d=await db(),t=d.transaction(STORE,mode),s=t.objectStore(STORE),value=await fn(s);await new Promise((ok,no)=>{t.oncomplete=ok;t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)});return value}
function req(r){return new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function put(x){return tx('readwrite',s=>req(s.put(x)))}async function get(id){return tx('readonly',s=>req(s.get(id)))}async function remove(id){let result=await tx('readwrite',s=>req(s.delete(id)));announce();return result}async function all(){return tx('readonly',s=>req(s.getAll()))}
function announce(){stats().then(x=>window.dispatchEvent(new CustomEvent('vcms-camera-queue',{detail:x}))).catch(()=>{})}
async function enqueue(x){x.status='pending';x.attempts=x.attempts||0;x.created_at=x.created_at||new Date().toISOString();x.updated_at=new Date().toISOString();await put(x);announce();return x}
async function pending(){return(await all()).filter(x=>x.status==='pending'||x.status==='failed'||x.status==='uploading')}
async function stats(){let rows=await all(),today=new Date().toISOString().slice(0,10),daily=rows.filter(x=>(x.created_at||'').slice(0,10)===today);return{total:daily.length,uploaded:daily.filter(x=>x.status==='uploaded').length,pending:rows.filter(x=>x.status==='pending'||x.status==='failed'||x.status==='uploading').length,uploading:rows.filter(x=>x.status==='uploading').length}}
async function syncOne(id){let x=await get(id);if(!x||x.status==='uploaded')return x;if(!navigator.onLine)throw Error('Offline — photo kept safely in Pending');x.status='uploading';x.updated_at=new Date().toISOString();await put(x);announce();try{if(typeof _vmmsEnsureFresh==='function')await _vmmsEnsureFresh();let s=getSession(),u=`${VMMS_CONFIG.BACKEND_URL}/api/v1/storage/upload?path=${encodeURIComponent(x.metadata.r2_object_key)}&content_type=image%2Fjpeg`,r=await fetch(u,{method:'PUT',headers:{Authorization:'Bearer '+s.access_token,'Content-Type':'image/jpeg'},body:x.blob});if(r.status===401&&typeof vmmsRefresh==='function'){await vmmsRefresh();s=getSession();r=await fetch(u,{method:'PUT',headers:{Authorization:'Bearer '+s.access_token,'Content-Type':'image/jpeg'},body:x.blob})}if(!r.ok)throw Error('Cloud upload failed');let saved=await r.json(),meta={...x.metadata,public_url:saved.public_url,uploaded_at:new Date().toISOString()},mr=await vmmsApi('/api/v1/camera/photos',{method:'POST',body:JSON.stringify(meta)});if(!mr.ok)throw Error((await mr.json().catch(()=>({}))).detail||'Photo Library update failed');x.status='uploaded';x.public_url=saved.public_url;x.metadata=meta;x.blob=null;x.error=null;x.updated_at=new Date().toISOString();await put(x);announce();return x}catch(e){x.status=(x.attempts||0)>=2?'failed':'pending';x.attempts=(x.attempts||0)+1;x.error=e.message||'Upload failed';x.updated_at=new Date().toISOString();await put(x);announce();throw e}}
async function syncAll(){if(syncing)return stats();syncing=true;try{for(let x of await pending()){try{await syncOne(x.photo_id)}catch(e){if(!navigator.onLine)break}}return stats()}finally{syncing=false;announce()}}
window.VCMSCameraQueue={enqueue,get,remove,all,pending,stats,syncOne,syncAll};window.addEventListener('online',()=>syncAll());setTimeout(()=>syncAll().catch(()=>{}),800);
})();
