(function(){
  let stream=null,facing='environment',source=null,files=[],fileIndex=0,scale=1,panX=0,panY=0,drag=null;
  const $=id=>document.getElementById(id),canvas=()=>$('cropCanvas'),ctx=()=>canvas().getContext('2d',{alpha:false});
  function ready(){return !$('cameraBtn')?.disabled}
  window.openCamera=async function(){if(!ready())return;show('Take photo');$('video').classList.remove('hidden');canvas().classList.add('hidden');$('shutter').classList.remove('hidden');$('flip').classList.remove('hidden');$('previewActions').classList.remove('show');$('cropTools').classList.add('hidden');try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1440}},audio:false});$('video').srcObject=stream}catch(e){closeCapture();toast(e?.name==='NotAllowedError'?'Camera permission denied. Enable Camera access in browser settings.':'Camera could not open. Use Gallery instead.')}};
  window.flipCamera=async function(){facing=facing==='environment'?'user':'environment';stop();await openCamera()};
  window.takePhoto=function(){let v=$('video');if(!v.videoWidth)return toast('Camera is still starting');let c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);source=c;stop();beginCrop('camera')};
  window.openGallery=function(){if(ready())$('galleryInput').click()};
  $('galleryInput').addEventListener('change',async e=>{files=[...e.target.files];fileIndex=0;if(!files.length)return;show('Crop gallery photo');await loadFile(files[0])});
  async function loadFile(file){let type=(file.type||'').toLowerCase(),name=file.name.toLowerCase();if(!(type.startsWith('image/')||/\.(heic|heif|jpg|jpeg|png)$/.test(name)))return fail('Unsupported image format');try{let url=URL.createObjectURL(file),im=new Image();await new Promise((ok,no)=>{im.onload=ok;im.onerror=no;im.src=url});URL.revokeObjectURL(url);source=im;beginCrop('gallery')}catch(e){fail(/\.(heic|heif)$/.test(name)?'This device could not decode the HEIC photo. Try selecting it from iPhone Photos again.':'The selected photo could not be opened.')}}
  function beginCrop(kind){$('video').classList.add('hidden');canvas().classList.remove('hidden');$('shutter').classList.add('hidden');$('flip').classList.add('hidden');$('cropTools').classList.remove('hidden');$('previewActions').classList.add('show');$('capTitle').textContent=kind==='camera'?'Preview photo':'Crop gallery photo';$('capCount').textContent=files.length?`${fileIndex+1} of ${files.length}`:'';scale=1;panX=0;panY=0;$('zoom').value=1;draw()}
  function dims(){return source instanceof HTMLCanvasElement?[source.width,source.height]:[source.naturalWidth,source.naturalHeight]}
  function draw(){if(!source)return;let [iw,ih]=dims(),cw=1600,ch=1200,base=Math.max(cw/iw,ch/ih),s=base*scale,dw=iw*s,dh=ih*s,maxX=Math.max(0,(dw-cw)/2),maxY=Math.max(0,(dh-ch)/2);panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));ctx().fillStyle='#000';ctx().fillRect(0,0,cw,ch);ctx().drawImage(source,(cw-dw)/2+panX,(ch-dh)/2+panY,dw,dh)}
  $('zoom').addEventListener('input',e=>{scale=+e.target.value;draw()});let frame=$('frame');frame.addEventListener('pointerdown',e=>{if(canvas().classList.contains('hidden'))return;drag={x:e.clientX,y:e.clientY,px:panX,py:panY};frame.setPointerCapture(e.pointerId)});frame.addEventListener('pointermove',e=>{if(!drag)return;let ratio=1600/frame.clientWidth;panX=drag.px+(e.clientX-drag.x)*ratio;panY=drag.py+(e.clientY-drag.y)*ratio;draw()});frame.addEventListener('pointerup',()=>drag=null);
  window.retake=function(){if(files.length)loadFile(files[fileIndex]);else{source=null;openCamera()}};
  window.acceptCrop=function(){canvas().toBlob(blob=>{window.vcmsCameraStage2Preview={blob,context:window.currentCameraContext(),capture_source:files.length?'gallery':'camera',captured_at:files.length?null:new Date().toISOString(),imported_at:files.length?new Date().toISOString():null,width:1600,height:1200};toast('4:3 photo ready. Stamp and upload are Stage 3.');if(files.length&&fileIndex<files.length-1){fileIndex++;loadFile(files[fileIndex])}else{closeCapture();files=[];$('galleryInput').value=''}},'image/jpeg',.92)};
  window.closeCapture=function(){stop();source=null;$('capture').classList.remove('open')};function stop(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('video').srcObject=null}function show(title){$('capture').classList.add('open');$('capTitle').textContent=title}function fail(s){closeCapture();toast(s)}
})();
