/* Lifting uses the existing signed-in session; all writes are server-authorised. */
(async function(){
'use strict';requireLogin();const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let DATA,ME,REVIEW=null,FILE=null,PREVIEW=null,REVIEWOCR=false,MOVE=null,PACKORDER=[],PACKSELECTED=new Set(),BUSY=false;
const BASE='/api/v1/lifting';
async function api(path='',options={}){const r=await vmmsApi(BASE+path,options);if(!r.ok){let d;try{d=await r.json()}catch{}throw Error(d?.detail||'Could not complete this action')}return r.json()}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const badge=s=>`<span class="badge ${esc(s).replace(/ /g,'-')}">${esc(s)}</span>`;
const machine=id=>DATA.machines.find(x=>x.id===id), cert=id=>DATA.gear_certificates.find(x=>x.id===id),holder=id=>machine(id)?.machine_id||'Store';
function opts(rows,label,blank='Choose a machine'){return `<option value="">${esc(blank)}</option>`+rows.map(x=>`<option value="${x.id}">${esc(label(x))}</option>`).join('')}
function section(s){if(!['directory','lm','lg','pack'].includes(s))s='directory';document.querySelectorAll('.lift-pane').forEach(x=>x.hidden=x.id!==s);document.querySelectorAll('[data-section]').forEach(x=>x.classList.toggle('on',x.dataset.section===s));$('section').value=s;history.replaceState(null,'','#'+s)}
document.querySelectorAll('[data-section]').forEach(x=>x.onclick=()=>section(x.dataset.section));$('section').onchange=e=>section(e.target.value);
async function refresh(){DATA=await api();render();$('notice').textContent=DATA.can_manage?'Records saved securely · Originals and history retained':'View access · Changes require an authorised coordinator';}
function grid(rows,columns,actions){if(!rows.length)return '<div class="lift-empty">No matching records yet.</div>';return `<div class="lift-table-wrap"><table class="lift-table"><thead><tr>${columns.map(x=>`<th>${esc(x[1])}</th>`).join('')}${actions?'<th>Actions</th>':''}</tr></thead><tbody>${rows.map(x=>`<tr>${columns.map(([k])=>`<td>${k==='status'?badge(x[k]):esc(x[k]??'—')}</td>`).join('')}${actions?`<td>${actions(x)}</td>`:''}</tr>`).join('')}</tbody></table></div><div class="lift-mobile-cards">${rows.map(x=>`<article class="lift-machine-card"><h3>${esc(x[columns[0][0]])}</h3><dl>${columns.slice(1).map(([k,t])=>`<dt>${esc(t)}</dt><dd>${k==='status'?badge(x[k]):esc(x[k]??'—')}</dd>`).join('')}</dl>${actions?actions(x):''}</article>`).join('')}</div>`}
const LM=[['machine_id','Machine ID'],['lm_number','LM No.'],['vehicle_number','Vehicle'],['equipment','Equipment'],['swl_kg','Max SWL (kg)'],['examination_date','Examination'],['validity_6','6 months'],['validity_12','12 months'],['certificate_expiry','Expiry'],['remarks','Remarks']];
const LG=[['lg_number','LG No.'],['gear_type','Gear type'],['size','Size'],['length','Length'],['swl_kg','SWL (kg)'],['examination_date','Examination'],['validity_6','6 months'],['validity_12','12 months'],['certificate_expiry','Expiry'],['next_renewal','Next renewal'],['currently_with','Currently with'],['remarks','Remarks']];
function machineActions(x){return `<button data-detail="${x.id}">Details</button> ${DATA.can_manage?`<button data-pack="${x.id}">Document pack</button>`:''}`}
function render(){document.querySelectorAll('.manage').forEach(x=>x.hidden=!DATA.can_manage);$('summary').innerHTML=[['Total machines',DATA.machines.length],['Valid',DATA.machines.filter(x=>x.status==='Valid').length],['Due soon',DATA.machines.filter(x=>x.status==='Due soon').length],['Expired',DATA.machines.filter(x=>x.status==='Expired').length]].map(([t,n])=>`<div><b>${n}</b><span>${t}</span></div>`).join('');renderMachines();$('lm-list').innerHTML=grid(DATA.machines,LM,machineActions);
let h=$('holder').value;$('holder').innerHTML=opts(DATA.machines,x=>x.machine_id,'All holders')+'<option value="store">Store</option>';$('holder').value=h;renderGears();
$('documents').innerHTML=DATA.documents.map(d=>`<div class="lift-item"><div><strong>${esc(d.original_filename)}</strong><small>${esc(d.kind)} · ${d.created_at.slice(0,10)} · ${d.verified?'Reviewed':'Awaiting review'} · ${esc(d.machine_id?holder(d.machine_id):d.gear_certificate_id?'Gear certificate':'Not linked yet')}${d.gear_certificate_id?' · '+esc(cert(d.gear_certificate_id)?.lg_number):''}</small></div><button data-file="${d.id}">View original</button>${!d.verified&&DATA.can_manage?`<button data-review="${d.id}">Review</button>`:''}</div>`).join('')||'<p>No documents uploaded yet.</p>';
$('attention').innerHTML=DATA.machines.flatMap(m=>{let w=[];if(m.status!=='Valid')w.push(`${m.machine_id}: ${m.status}`);if(!DATA.documents.some(d=>d.machine_id===m.id&&d.kind==='load_chart'&&d.verified))w.push(`${m.machine_id}: missing reviewed load chart`);return w}).concat(DATA.gear_certificates.filter(g=>g.status!=='Valid').map(g=>`${g.lg_number}: ${g.status}`),DATA.documents.filter(d=>!d.verified).map(d=>`${d.original_filename}: awaiting review`)).map(w=>`<p>${esc(w)}</p>`).join('')||'<p>No outstanding document alerts.</p>';
$('movement-history').innerHTML=DATA.movements.map(m=>{let i=DATA.gear_items.find(i=>i.id===m.item_id);return `<div class="lift-item"><div>${esc(cert(i?.certificate_id)?.lg_number)} · ${esc(i?.marking)}<small>${esc(m.action)} · ${esc(holder(m.from_machine_id))} → ${esc(holder(m.to_machine_id))} · ${new Date(m.moved_at).toLocaleString()}<br>${esc(m.issued_by)} → ${esc(m.received_by)} · ${esc(m.remarks)}</small></div></div>`}).join('')||'<p>No movements recorded.</p>';
let p=$('pack-machine').value;$('pack-machine').innerHTML=opts(DATA.machines,x=>`${x.machine_id} · ${x.vehicle_number} · ${x.lm_number}`);$('pack-machine').value=p;if(p)buildPack();
$('pack-history').innerHTML=DATA.packs.map(p=>`<div class="lift-item"><div>${esc(holder(p.machine_id))}<small>${new Date(p.generated_at).toLocaleString()} · Frozen snapshot</small></div><button data-pack-pdf="${p.id}">Download PDF</button></div>`).join('')||'<p>No packs generated yet.</p>';
}
function renderMachines(){let q=$('search').value.toLowerCase(),s=$('status').value;let rows=DATA.machines.filter(m=>(!s||m.status===s)&&[m.machine_id,m.lm_number,m.vehicle_number,m.equipment].join(' ').toLowerCase().includes(q));$('machine-list').innerHTML=grid(rows,[['machine_id','Machine ID'],['vehicle_number','Vehicle'],['equipment','Equipment'],['swl_kg','Max SWL (kg)'],['lm_number','LM Certificate'],['certificate_expiry','Expiry'],['status','Status']],machineActions)}
function gearRows(){return DATA.gear_items.map(i=>({...cert(i.certificate_id),item_id:i.id,marking:i.marking,current_machine_id:i.current_machine_id,currently_with:holder(i.current_machine_id)+' · '+i.marking,condition:i.condition}))}
function renderGears(){const q=$('gear-search').value.toLowerCase(),h=$('holder').value;const rows=gearRows().filter(g=>(!h||(h==='store'?!g.current_machine_id:g.current_machine_id===h))&&[g.lg_number,g.gear_type,g.marking].join(' ').toLowerCase().includes(q));$('lg-list').innerHTML=grid(rows,LG,x=>`${badge(x.status)} ${DATA.can_manage?`<button data-move="${x.item_id}">Issue / Borrow / Return</button>`:''}`)}
$('search').oninput=renderMachines;$('status').onchange=renderMachines;$('gear-search').oninput=renderGears;$('holder').onchange=renderGears;
async function download(path,name){const r=await vmmsApi(BASE+path);if(!r.ok){let d=await r.json();throw Error(d.detail||'Download failed')}const u=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000)}
function downloadLog(kind){return download(`/logs/${kind}/pdf`,kind+'-log.pdf')}
$('machine-print').onclick=$('lm-print').onclick=()=>run(()=>downloadLog('machines'));$('lg-print').onclick=()=>run(()=>downloadLog('gears'));
$('machine-export').onclick=()=>{let cols=[...LM,['status','Status']],rows=[cols.map(x=>x[1]),...DATA.machines.map(m=>cols.map(([k])=>m[k]??''))];let csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replace(/"/g,'""')+'"').join(',')).join('\r\n');let u=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='lifting-machine-list.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
async function run(fn){try{await fn()}catch(e){$('notice').textContent=e.message}}
function field(name,title,type='text',required=false,value=''){return `<label>${esc(title)}<input name="${name}" type="${type}" ${required?'required':''} ${type==='number'?'min="0.001" step="any"':''} maxlength="500" value="${esc(value)}"></label>`}
function reviewFields(data={}){let kind=$('review-form').elements.kind.value,html='';if(kind==='lm'){html=field('machine_id','Machine ID (enter manually)','text',true,data.machine_id)+field('lm_number','LM registration number','text',true,data.lm_number)+field('vehicle_number','Vehicle number','text',true,data.vehicle_number)+field('equipment','Equipment / make / model','text',true,data.equipment)+field('swl_kg','Maximum certificate SWL (kg)','number',true,data.swl_kg)+field('owner','Owner (matching details)','text',false,data.owner)+field('serial_number','Distinctive / serial number','text',true,data.serial_number)}else if(kind==='lg'){html=field('lg_number','LG registration number','text',true,data.lg_number)+field('quantity','Number of physical items on certificate','number',true,data.quantity)+`<label>Gear type<select name="gear_type">${['Bow screw pin shackle','Webbing sling','Chain sling','Wire rope sling','Other'].map(t=>`<option ${data.gear_type===t?'selected':''}>${t}</option>`).join('')}</select></label>`+field('size','Size / diameter','text',false,data.size)+field('length','Length','text',false,data.length)+field('swl_kg','Certificate SWL (kg)','number',true,data.swl_kg)+`<label>Applicable renewal interval<select name="renewal_months"><option value="6">6 months</option><option value="12" ${data.renewal_months===12?'selected':''}>12 months</option></select></label>`+field('renewal_reason','Reason for selected interval','text',true,data.renewal_reason)+`<label>Physical item markings (one per line)<textarea name="markings" required rows="3">${esc((data.markings||[]).join('\n'))}</textarea></label>`}if(['lm','lg'].includes(kind))html+=field('examination_date','Last thorough examination','date',true,data.examination_date)+field('certificate_expiry','Printed certificate expiry','date',true,data.certificate_expiry);html+=field('remarks','Remarks','text',false,data.remarks);$('review-fields').innerHTML='<div class="lift-field-grid">'+html+'</div>';let rows=kind==='lm'?DATA.machines:kind==='lg'?DATA.gear_certificates:DATA.machines;$('review-target').innerHTML=opts(rows,x=>kind==='lg'?x.lg_number:`${x.machine_id} · ${x.lm_number}`,['lm','lg'].includes(kind)?'New certificate record':'Choose linked machine');}
function cleanupPreview(){if(PREVIEW)URL.revokeObjectURL(PREVIEW);PREVIEW=null;$('original-preview').replaceChildren()}
function preview(blob){cleanupPreview();PREVIEW=URL.createObjectURL(blob);let el=document.createElement(blob.type==='application/pdf'?'iframe':'img');el.src=PREVIEW;el.title='Original certificate';el.alt='Original certificate';$('original-preview').appendChild(el);let a=document.createElement('a');a.href=PREVIEW;a.target='_blank';a.rel='noopener';a.textContent='Open original in a new tab';$('original-preview').appendChild(a)}
async function openReview(kind='lm',d=null){REVIEW=d;FILE=null;REVIEWOCR=false;$('file').disabled=false;$('review-form').reset();$('review-form').elements.kind.value=d?.kind||kind;$('review-form').elements.kind.disabled=!!d;$('file-wrap').hidden=!!d;$('extract-progress').textContent='All extracted values require your review.';$('review-error').textContent='';$('review-save').disabled=!d;cleanupPreview();reviewFields();$('review-dialog').showModal();if(d){const r=await vmmsApi(BASE+`/documents/${d.id}/file`);if(!r.ok)throw Error('Could not open original');FILE=await r.blob();preview(FILE);await readFile(FILE)}}
$('upload').onclick=()=>run(()=>openReview());$('lm-upload').onclick=()=>run(()=>openReview('lm'));$('lg-upload').onclick=()=>run(()=>openReview('lg'));$('review-dialog').addEventListener('cancel',e=>{if(BUSY)e.preventDefault()});$('review-close').onclick=()=>{if(BUSY)return;$('review-dialog').close();cleanupPreview()};$('review-form').elements.kind.onchange=()=>reviewFields();$('review-target').onchange=()=>{let id=$('review-target').value,k=$('review-form').elements.kind.value,x=k==='lg'?cert(id):machine(id);if(!x)return;let values={...x,markings:DATA.gear_items.filter(i=>i.certificate_id===id).map(i=>i.marking)};let current=Object.fromEntries(new FormData($('review-form')));reviewFields({...values,...Object.fromEntries(Object.entries(current).filter(([k,v])=>v&& !['target_id','kind','markings','confirmed'].includes(k)))});$('review-target').value=id;};
async function readFile(file){BUSY=true;$('review-save').disabled=true;let text='',ocr=false,worker=null;async function recognise(image){if(!worker){worker=await Tesseract.createWorker('eng');await worker.setParameters({tessedit_pageseg_mode:'11'})}return worker.recognize(image)}try{if(file.type==='application/pdf'){pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';let pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise;if(pdf.numPages>150)throw Error('PDF exceeds 150 pages');for(let n=1;n<=pdf.numPages;n++){let p=await pdf.getPage(n),tc=await p.getTextContent(),t=tc.items.map(i=>i.str).join(' ');$('extract-progress').textContent=`Reading page ${n} of ${pdf.numPages}…`;if(t.trim().length<30){let vp=p.getViewport({scale:2.7}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;let result=await recognise(c);t=result.data.text;ocr=true}text+=t+'\n';if(text.length>100000)text=text.slice(0,100000)}await pdf.destroy()}else{let r=await recognise(file);text=r.data.text;ocr=true}REVIEWOCR=ocr;let result=await post('/extract',{text:text.slice(0,100000)});let k=$('review-form').elements.kind.value;reviewFields(result.fields);$('review-form').elements.extracted_text.value=text.slice(0,100000);$('extract-progress').textContent=(ocr?'OCR completed. ':'Text extracted. ')+result.warnings.join(' ')}catch(e){$('extract-progress').textContent='Automatic extraction could not complete. Enter the fields manually and review the original. '+e.message}finally{if(worker)await worker.terminate();BUSY=false;$('review-save').disabled=false}}
$('file').onchange=async e=>{let file=e.target.files[0];if(!file)return;if(file.size>20971520){$('review-error').textContent='Use a document no larger than 20 MB';return}FILE=file;preview(file);await readFile(file)};
$('review-form').onsubmit=async e=>{e.preventDefault();if(BUSY||!FILE)return;BUSY=true;$('review-save').disabled=true;$('review-error').textContent='';try{const form=$('review-form'),values=Object.fromEntries(new FormData(form)),kind=form.elements.kind.value;values.confirmed=form.elements.confirmed.checked;values.ocr_used=REVIEWOCR;if(values.markings)values.markings=values.markings.split('\n').map(v=>v.trim()).filter(Boolean);if(values.renewal_months)values.renewal_months=Number(values.renewal_months);if(!REVIEW){REVIEW=await api(`/documents?kind=${encodeURIComponent(kind)}&filename=${encodeURIComponent(FILE.name||'certificate.'+(FILE.type==='application/pdf'?'pdf':'png'))}`,{method:'POST',headers:{'Content-Type':FILE.type},body:FILE});form.elements.kind.disabled=true;$('file').disabled=true}await post(`/documents/${REVIEW.id}/review`,{data:values,target_id:form.elements.target_id.value||null});$('review-dialog').close();cleanupPreview();await refresh();$('notice').textContent='Certificate reviewed and saved. Previous versions retained.'}catch(e){$('review-error').textContent=e.message}finally{BUSY=false;$('review-save').disabled=false}};
async function detail(id){let m=machine(id);$('detail-title').textContent=m.machine_id+' · '+m.vehicle_number;let gears=gearRows().filter(g=>g.current_machine_id===id),docs=DATA.documents.filter(d=>d.machine_id===id);$('detail-body').innerHTML=`<p>${esc(m.equipment)} · ${badge(m.status)}</p><p>LM ${esc(m.lm_number)} · Maximum certificate SWL ${esc(m.swl_kg)} kg</p><h3>Assigned gears</h3>${gears.map(g=>`<p>${esc(g.lg_number)} · ${esc(g.marking)} · ${badge(g.status)}</p>`).join('')||'<p>No gears currently assigned.</p>'}<h3>Documents and renewal history</h3>${docs.map(d=>`<div class="lift-item"><div>${esc(d.original_filename)}<small>${d.created_at.slice(0,10)} · ${d.id===m.current_document_id?'Current LM certificate':d.kind==='lm'?'Previous LM version':esc(d.kind)}</small></div><button data-file="${d.id}">View</button></div>`).join('')} ${DATA.can_manage?`<button class="primary" data-pack="${m.id}">Generate Client Document Pack</button>`:''}`;$('detail-dialog').showModal()}
$('detail-close').onclick=()=>$('detail-dialog').close();$('move-close').onclick=()=>$('move-dialog').close();
function openMove(id){MOVE=DATA.gear_items.find(i=>i.id===id);$('move-form').reset();$('move-context').textContent=`${cert(MOVE.certificate_id).lg_number} · ${MOVE.marking} · Currently with ${holder(MOVE.current_machine_id)}`;$('move-to').innerHTML=opts(DATA.machines.filter(m=>m.id!==MOVE.current_machine_id),m=>m.machine_id,'Store');$('move-error').textContent='';$('move-dialog').showModal()}
$('move-form').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;try{let values=Object.fromEntries(new FormData(e.target));await post(`/items/${MOVE.id}/move`,{...values,from_machine_id:MOVE.current_machine_id,to_machine_id:values.to_machine_id||null});$('move-dialog').close();await refresh();$('notice').textContent='Movement recorded. Current holder updated.'}catch(e){$('move-error').textContent=e.message}finally{b.disabled=false}};
function packData(){let id=$('pack-machine').value,m=machine(id);if(!m)return null;let items=DATA.gear_items.filter(i=>i.current_machine_id===id&&i.condition==='available'),docs=DATA.documents.filter(d=>d.machine_id===id&&(d.kind!=='lm'||d.id===m.current_document_id));for(let i of items){let c=cert(i.certificate_id),d=DATA.documents.find(d=>d.id===c.current_document_id);if(d&&!docs.some(x=>x.id===d.id))docs.push(d)}return {m,items,docs}}
function buildPack(){let p=packData();if(!p){$('pack-options').innerHTML='';return}PACKORDER=['lm_log','lg_log',...p.docs.sort((a,b)=>({lm:0,load_chart:1,lg:2,supporting:3}[a.kind]-{lm:0,load_chart:1,lg:2,supporting:3}[b.kind])).map(d=>d.id)];PACKSELECTED=new Set(PACKORDER);let warnings=[];if(p.m.status!=='Valid')warnings.push('Machine certificate: '+p.m.status);if(!p.docs.some(d=>d.kind==='load_chart'&&d.verified))warnings.push('No reviewed load chart');for(let i of p.items){let c=cert(i.certificate_id);if(c.status!=='Valid')warnings.push(`${c.lg_number} · ${i.marking}: ${c.status}`)}p.docs.filter(d=>!d.verified).forEach(d=>warnings.push(`${d.original_filename}: unverified`));$('pack-options').innerHTML=`<div class="lift-card"><h3>Gears currently with this machine</h3>${p.items.map(i=>`<label class="check"><input type="checkbox" data-pack-item="${i.id}" checked>${esc(cert(i.certificate_id).lg_number)} · ${esc(i.marking)}</label>`).join('')||'<p>No assigned gears.</p>'}<h3>Document order</h3><p class="muted">Logs come first by default. Include or exclude originals and change their order below.</p><ul id="pack-order" class="pack-order"></ul>${warnings.length?`<div class="pack-warnings">${warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</div>`:''}<label class="check"><input type="checkbox" id="pack-ack">I reviewed and acknowledge missing, expired or unverified documents and any excluded documents.</label><button class="primary" id="generate-pack" ${DATA.can_manage?'':'disabled'}>Generate PDF pack</button><p id="pack-result" role="status"></p></div>`;renderOrder();$('generate-pack').onclick=generatePack;}
function renderOrder(){let p=packData();function info(k){let d=p.docs.find(d=>d.id===k);if(!d)return '';let c=d.kind==='lg'?cert(d.gear_certificate_id):p.m;return `<small>${esc(c.lg_number||c.lm_number||'')} · ${d.kind==='lm'||d.kind==='lg'?'Expiry '+esc(c.certificate_expiry||'missing')+' · ':''}${d.verified?'Reviewed':'Unverified'} · Uploaded ${esc(d.created_at.slice(0,10))} · Version ${esc(d.id.slice(0,8))}</small>`} $('pack-order').innerHTML=PACKORDER.map((k,n)=>`<li>${['lm_log','lg_log'].includes(k)?'':`<input aria-label="Include ${esc(p.docs.find(d=>d.id===k)?.original_filename)}" type="checkbox" data-pack-doc="${k}" ${PACKSELECTED.has(k)?'checked':''}>`}<span>${esc({lm_log:'LM Log',lg_log:'LG Log'}[k]||p.docs.find(d=>d.id===k)?.original_filename)}${info(k)}</span><button data-order="${n}" data-direction="-1" aria-label="Move document up" ${n===0?'disabled':''}>↑</button><button data-order="${n}" data-direction="1" aria-label="Move document down" ${n===PACKORDER.length-1?'disabled':''}>↓</button></li>`).join('')}
$('pack-machine').onchange=buildPack;
async function generatePack(){let button=$('generate-pack');button.disabled=true;try{let p=packData(),items=Array.from(document.querySelectorAll('[data-pack-item]:checked')).map(x=>x.dataset.packItem),docs=p.docs.filter(d=>PACKSELECTED.has(d.id)&&(!d.gear_certificate_id||p.items.some(i=>items.includes(i.id)&&i.certificate_id===d.gear_certificate_id))).map(d=>d.id);let order=PACKORDER.filter(k=>['lm_log','lg_log'].includes(k)||docs.includes(k));let pack=await post('/packs',{machine_id:p.m.id,item_ids:items,document_ids:docs,order,acknowledge_warnings:$('pack-ack').checked});await download(`/packs/${pack.id}/pdf`,'lifting-client-pack.pdf');await refresh();$('notice').textContent='PDF downloaded. A frozen pack snapshot was saved.'}catch(e){$('pack-result').textContent=e.message}finally{button.disabled=false}}
document.addEventListener('change',e=>{if(e.target.dataset.packDoc){if(e.target.checked)PACKSELECTED.add(e.target.dataset.packDoc);else PACKSELECTED.delete(e.target.dataset.packDoc)}});
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;run(async()=>{if(b.dataset.detail)await detail(b.dataset.detail);if(b.dataset.pack){$('detail-dialog').close();section('pack');$('pack-machine').value=b.dataset.pack;buildPack()}if(b.dataset.file){let r=await vmmsApi(BASE+`/documents/${b.dataset.file}/file`);if(!r.ok)throw Error('Could not load original');$('detail-title').textContent='Original document';$('detail-body').innerHTML='<div id="file-view"></div>';let u=URL.createObjectURL(await r.blob()),iframe=document.createElement('iframe');iframe.src=u;iframe.title='Original document';iframe.style.cssText='width:100%;height:65vh;border:0';$('file-view').appendChild(iframe);$('detail-dialog').showModal();$('detail-dialog').addEventListener('close',()=>URL.revokeObjectURL(u),{once:true})}if(b.dataset.review)await openReview('lm',DATA.documents.find(d=>d.id===b.dataset.review));if(b.dataset.move)openMove(b.dataset.move);if(b.dataset.packPdf)await download(`/packs/${b.dataset.packPdf}/pdf`,'lifting-client-pack.pdf');if(b.dataset.order!==undefined){let n=Number(b.dataset.order),to=n+Number(b.dataset.direction);[PACKORDER[n],PACKORDER[to]]=[PACKORDER[to],PACKORDER[n]];renderOrder()}})});
try{let r=await vmmsApi('/api/v1/me');if(!r.ok)throw Error('Please sign in again');ME=await r.json();await refresh();section(location.hash.slice(1))}catch(e){$('notice').textContent=e.message}
})();
