(function(){"use strict";var activities=[],relationships=[],canEdit=false;
function e(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function projectId(){return window.vcmsProjectContext&&vcmsProjectContext.requireActiveId()}
async function load(){try{await vcmsProjectContext.init();var id=projectId(),rs=await Promise.all([vmmsApi("/api/v1/me"),vmmsApi("/api/v1/schedule/activities?project_id="+encodeURIComponent(id)),vmmsApi("/api/v1/schedule/relationships?project_id="+encodeURIComponent(id))]);if(!rs[1].ok||!rs[2].ok)throw new Error("Could not load activity logic");var me=await rs[0].json();canEdit=isFull(me.role)||isManager(me.role);activities=(await rs[1].json()).activities||[];relationships=(await rs[2].json()).relationships||[];document.getElementById("add-relationship").classList.toggle("hidden",!canEdit||activities.length<2);render()}catch(x){document.getElementById("logic-empty").textContent=x.message;document.getElementById("logic-empty").classList.remove("hidden")}}
function render(){var map={};activities.forEach(function(a){map[a.id]=a});document.getElementById("logic-body").innerHTML=relationships.map(function(r){var p=map[r.predecessor_id]||{},s=map[r.successor_id]||{},lag=r.lag_days===0?"0 days":(r.lag_days>0?"+":"")+r.lag_days+" days";return'<tr><td><strong>'+e(p.code||"?")+'</strong><div class="muted">'+e(p.name||"Unavailable")+'</div></td><td><span class="type-pill">'+e(r.relationship_type)+'</span></td><td>'+e(lag)+'</td><td><strong>'+e(s.code||"?")+'</strong><div class="muted">'+e(s.name||"Unavailable")+'</div></td><td>'+(canEdit?'<button class="border rounded-lg px-3 py-1" data-remove-logic="'+r.id+'">Remove</button>':'')+'</td></tr>'}).join("");document.getElementById("logic-empty").classList.toggle("hidden",relationships.length>0);document.getElementById("logic-table").classList.toggle("hidden",relationships.length===0);document.querySelectorAll("[data-remove-logic]").forEach(function(b){b.onclick=function(){remove(b.dataset.removeLogic)}})}
function options(){return activities.map(function(a){return'<option value="'+a.id+'">'+e(a.code+" — "+a.name)+'</option>'}).join("")}
function open(){document.getElementById("logic-predecessor").innerHTML=options();document.getElementById("logic-successor").innerHTML=options();if(activities[1])document.getElementById("logic-successor").value=activities[1].id;document.getElementById("logic-type").value="FS";document.getElementById("logic-lag").value=0;document.getElementById("logic-modal").classList.remove("hidden")}
function close(){document.getElementById("logic-modal").classList.add("hidden");document.getElementById("logic-error").classList.add("hidden")}
async function remove(id){if(!confirm("Remove this activity relationship?"))return;var r=await vmmsApi("/api/v1/schedule/relationships/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_active:false})});if(!r.ok)return alert("Could not remove relationship");await load()}
function show(){["wbs-panel","activities-panel","calendars-panel","resources-panel"].forEach(function(id){document.getElementById(id).classList.add("hidden")});document.getElementById("logic-panel").classList.remove("hidden");document.querySelectorAll(".schedule-tabs button").forEach(function(b){b.classList.remove("active")});document.getElementById("tab-logic").classList.add("active");document.getElementById("add").classList.add("hidden");load()}
document.getElementById("tab-logic").onclick=show;document.getElementById("add-relationship").onclick=open;document.getElementById("logic-cancel").onclick=close;document.getElementById("logic-form").onsubmit=async function(ev){ev.preventDefault();var predecessor=document.getElementById("logic-predecessor").value,successor=document.getElementById("logic-successor").value,er=document.getElementById("logic-error");if(predecessor===successor){er.textContent="Select two different activities";er.classList.remove("hidden");return}var r=await vmmsApi("/api/v1/schedule/relationships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({project_id:projectId(),predecessor_id:predecessor,successor_id:successor,relationship_type:document.getElementById("logic-type").value,lag_days:Number(document.getElementById("logic-lag").value)})});if(!r.ok){var d=await r.json();er.textContent=Array.isArray(d.detail)?d.detail.map(function(x){return x.msg}).join("; "):d.detail||"Relationship rejected";er.classList.remove("hidden");return}close();await load()};window.addEventListener("vcms:project-changed",load);load();})();
