/* Tipper register, versioned client/site rules, driver links and review dialogs. */
requireLogin();
(()=>{
  async function api(path,opts){const r=await vmmsApi(path,opts);if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(typeof e.detail==='string'?e.detail:`Request failed (${r.status})`);}return r.status===204?{}:r.json();}
  const $=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)],T=Tipper,E=T.esc,M=T.money;
  const base='/api/v1/equipment/tipper';let SETUP={clients:[],providers:[],drivers:[],work_types:[]},RULES=[],TRIPS=[],PENDING=[],REVIEW=[],MONTH='',edit=null,masterKind='',masterID=null,busy=false,BATCH_ID='';
  const names={day:'Day Work',night:'Night Work',trip:'Trip Basis',legacy:'Legacy record'};
  function message(s){$('page-alert').textContent=s;$('page-alert').classList.toggle('tt-hidden',!s);}
  function pane(id){qa('.tt-pane').forEach(p=>p.classList.toggle('on',p.id===id));qa('.tt-tab').forEach(b=>b.classList.toggle('on',b.dataset.pane===id));$('rate-directory').hidden=id!=='masters';$('export-filters').hidden=!['register','report'].includes(id);}
  qa('.tt-tab').forEach(b=>b.onclick=()=>pane(b.dataset.pane));qa('[data-open]').forEach(b=>b.onclick=()=>pane(b.dataset.open));
  const options=(rows,value,blank='Choose…')=>'<option value="">'+E(blank)+'</option>'+rows.filter(r=>r.active!==false).map(r=>`<option value="${E(r.id)}" ${r.id===value?'selected':''}>${E(r.name)}</option>`).join('');
  function field(name,label,value='',type='text',required=false,extra=''){return `<div class="tt-field"><label for="f-${E(name)}">${E(label)}</label><input id="f-${E(name)}" name="${E(name)}" type="${type}" value="${E(value??'')}" ${required?'required':''} ${extra}></div>`;}
  function select(name,label,rows,value='',required=true){return `<div class="tt-field"><label for="f-${E(name)}">${E(label)}</label><select id="f-${E(name)}" name="${E(name)}" ${required?'required':''}>${options(rows,value)}</select></div>`;}
  function workId(mode){const match=SETUP.work_types.find(r=>r.active!==false&&(mode==='trip'?/trip/i.test(r.name):mode==='day'?/day/i.test(r.name):/night/i.test(r.name)));return match?.id||'';}
  function displayMode(row){return row.billing_mode==='legacy'?(row.work_type?.name||'Legacy record'):(names[row.billing_mode]||row.work_type?.name||'—');}
  function workMode(r){if(r.billing_mode&&r.billing_mode!=='legacy')return r.billing_mode;const n=String(r.work_type?.name||'').toLowerCase();return n.includes('trip')?'trip':n.includes('night')?'night':n.includes('day')?'day':'legacy';}
  function workMatches(r){const f=$('work-filter').value,m=workMode(r);return f==='all'||(f==='day-night'?['day','night'].includes(m):f===m);}
  function periodParams(){return $('period-mode').value==='range'?new URLSearchParams({date_from:$('date-from').value,date_to:$('date-to').value}):new URLSearchParams({month:MONTH});}
  $('period-mode').onchange=()=>{const range=$('period-mode').value==='range';$('range-from').hidden=!range;$('range-to').hidden=!range;qa('.js-month').forEach(e=>e.disabled=range);if(!range||($('date-from').value&&$('date-to').value))load();};
  $('date-from').onchange=$('date-to').onchange=()=>{if($('date-from').value&&$('date-to').value)load();};$('work-filter').onchange=()=>{renderRegister();renderReport();};
  function rowsFiltered(){return TRIPS.filter(r=>workMatches(r)&&(!$('report-client').value||r.client_id===$('report-client').value)&&(!$('report-provider').value||r.provider_id===$('report-provider').value)&&(!$('report-site').value||r.site_name===$('report-site').value));}
  function renderRegister(){const search=$('trip-search').value.toLowerCase();const rows=[...PENDING.map(s=>({...s.confirmed_data,id:s.id,pending:true,submission:s,driver:s.driver,client:SETUP.clients.find(r=>r.id===s.confirmed_data?.client_id),provider:SETUP.providers.find(r=>r.id===s.driver?.provider_id)})),...TRIPS];
    $('register-rows').innerHTML=rows.filter(r=>workMatches(r)&&JSON.stringify(r).toLowerCase().includes(search)).map(r=>{
      const h=v=>v==null?'—':Number(v).toFixed(2),amount=r.pending?null:r.transport_amount;
      return `<tr class="${r.pending?'pending':''}"><td>${E(r.trip_date)}</td><td>${E(r.do_no)}</td><td><b>${E(r.truck_no)}</b></td><td>${E(r.client?.name)}<br><small>${E(r.site_name)}</small></td><td>${E(r.provider?.name)}</td><td>${E(displayMode(r))}${r.pending?'<br><span class="tt-badge warn">Pending Review</span>':''}${r.billing_mode==='trip'?`<br><small>${Number(r.quantity)} trips</small>`:''}</td><td>${E([r.pickup_location,r.delivery_location].filter(Boolean).join(' → '))}</td><td>${E(r.start_time?.slice(0,5)||'—')}</td><td>${E(r.end_time?.slice(0,5)||'—')}</td><td>${h(r.normal_hours)}</td><td>${h(r.ot_hours)}</td><td>${h(r.total_hours)}</td><td>${M(r.transport_rate)}${r.billing_mode==='day'||r.billing_mode==='night'?`<br><small>OT ${M(r.ot_rate)}</small>`:''}</td><td>${amount==null?'Pending':M(amount)}</td><td>${SETUP.can_manage?`<button class="tt-btn small ghost" data-edit="${E(r.id)}" data-pending="${r.pending?'yes':'no'}">${r.pending?'Review':'Edit'}</button>${r.pending?`<button class="tt-btn small danger" data-reject="${E(r.id)}">Reject</button>`:`<button class="tt-btn small danger" data-delete="${E(r.id)}">Delete</button>`}`:'—'}</td></tr>`;
    }).join('')||'<tr><td colspan="15" class="tt-empty">No matching trips</td></tr>';
    $('register-rows').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>b.dataset.pending==='yes'?openTrip(PENDING.find(x=>x.id===b.dataset.edit),'pending'):openTrip(TRIPS.find(x=>x.id===b.dataset.edit),'edit'));
    $('register-rows').querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{if(!confirm('Reject this driver submission?'))return;try{await api(base+'/submissions/'+b.dataset.reject+'/reject',{method:'POST'});await load();}catch(e){message(e.message);}});
    $('register-rows').querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this approved trip permanently?'))return;try{await api(base+'/trips/'+b.dataset.delete,{method:'DELETE'});await load();}catch(e){message(e.message);}});
  }
  function renderReport(){const rows=rowsFiltered(),groups=new Map();for(const r of rows){const k=r.truck_no+'|'+r.provider_id;let g=groups.get(k)||{truck:r.truck_no,provider:r.provider?.name,n:0,h:0,t:0,a:0,hasHours:false,legacy:0};g.n++;g.h+=Number(r.total_hours||0);if(r.total_hours!=null)g.hasHours=true;if(r.billing_mode==='legacy')g.legacy++;if(r.billing_mode==='trip')g.t+=Number(r.quantity||0);g.a+=Number(r.transport_amount||0);groups.set(k,g);}
    $('summary-rows').innerHTML=[...groups.values()].map(r=>`<tr><td>${E(r.truck)}</td><td>${E(r.provider)}</td><td>${r.n}</td><td>${[r.hasHours?r.h.toFixed(2)+' hours':'',r.t?r.t+' trips':'',r.legacy?r.legacy+' legacy '+(r.legacy===1?'entry':'entries'):''].filter(Boolean).join(' · ')||'—'}</td><td>${M(r.a)}</td></tr>`).join('')||'<tr><td colspan="5" class="tt-empty">No approved records</td></tr>';
    $('report-total').textContent=M(rows.reduce((a,r)=>a+Number(r.transport_amount||0),0));$('report-meta').textContent=rows.length+' approved entries · '+new Set(rows.map(r=>r.truck_no)).size+' trucks';
  }
  function render(){renderRegister();renderReport();$('k-entries').textContent=TRIPS.length;$('k-trucks').textContent=new Set(TRIPS.map(r=>r.truck_no)).size;$('k-qty').textContent=PENDING.length;$('k-amount').textContent=M(TRIPS.reduce((a,r)=>a+Number(r.transport_amount||0),0));
    $('recent-rows').innerHTML=TRIPS.slice(-8).reverse().map(r=>`<tr><td>${E(r.trip_date)}</td><td>${E(r.trip_sheet_no)}</td><td>${E(r.truck_no)}</td><td>${E(r.client?.name)}</td><td>${M(r.transport_amount)}</td></tr>`).join('')||'<tr><td colspan="5" class="tt-empty">No approved trips</td></tr>';
  }
  async function load(){try{[TRIPS,PENDING]=await Promise.all([api(base+'/trips?'+periodParams()),api(base+'/submissions?'+periodParams())]);render();message('');}catch(e){message(e.message);}}
  function filterSites(){const client=$('report-client').value,current=$('report-site').value,sites=[...new Set([...RULES,...TRIPS].filter(r=>!client||r.client_id===client).map(r=>r.site_name).filter(Boolean))];$('report-site').innerHTML='<option value="">All sites</option>'+sites.map(s=>`<option value="${E(s)}">${E(s)}</option>`).join('');if(sites.includes(current))$('report-site').value=current;renderReport();}
  $('trip-search').oninput=renderRegister;$('report-client').onchange=filterSites;$('report-provider').onchange=renderReport;$('report-site').onchange=renderReport;
  qa('.js-month').forEach(x=>x.onchange=()=>{if(!x.value)return;MONTH=x.value;qa('.js-month').forEach(y=>y.value=MONTH);load();});
  function editData(){const f=$('edit-form').elements,get=n=>f[n]?.value??'';return {client_id:get('client_id'),provider_id:get('provider_id'),driver_id:get('driver_id')||null,driver_name:edit.row?.driver_name||edit.row?.driver?.name||null,work_type_id:get('billing_mode')==='legacy'?edit.row.work_type_id:workId(get('billing_mode')),billing_mode:get('billing_mode'),site_name:get('site_name'),trip_date:get('trip_date'),trip_sheet_no:get('trip_sheet_no')||get('do_no'),do_no:get('do_no'),truck_no:get('truck_no'),pickup_location:get('pickup_location'),delivery_location:get('delivery_location'),material_type:edit.row?.material_type||'',quantity:Number(get('quantity')||1),unit_type:get('billing_mode')==='legacy'?(edit.row.unit_type||'load'):get('billing_mode')==='trip'?'trip':'hour',start_time:get('start_time')||null,end_time:get('end_time')||null,break_minutes:Number(get('break_minutes')||0),transport_rate:Number(get('transport_rate')),ot_rate:get('ot_rate')===''?null:Number(get('ot_rate')),rate_snapshot:edit.snapshot||edit.row?.rate_snapshot||{},source:edit.row?.source||'manual',source_image_url:edit.row?.source_image_url||null,source_image_key:edit.row?.source_image_key||null,extraction_confidence:edit.row?.extraction_confidence||null};}
  function previewEdit(){const d=editData(),v=T.totals(d),form=$('edit-form').elements,trip=d.billing_mode==='trip',legacy=d.billing_mode==='legacy';
    for(const n of ['start_time','end_time','break_minutes','ot_rate']){form[n].closest('.tt-field').classList.toggle('tt-hidden',trip||legacy);form[n].required=!trip&&!legacy&&(n==='start_time'||n==='end_time'||(n==='ot_rate'&&v.ot>0));}
    form.quantity.closest('.tt-field').classList.toggle('tt-hidden',!trip&&!legacy);form.quantity.required=trip||legacy;
    $('edit-preview').textContent=(trip?'Trips: '+d.quantity:legacy?'Legacy quantity: '+d.quantity:`Basic ${v.normal.toFixed(2)} h · OT ${v.ot.toFixed(2)} h · Total ${v.total.toFixed(2)} h`)+` · Amount ${M(v.amount)}`;
  }
  function applyRule(){const f=$('edit-form').elements,d=editData(),r=T.rule(RULES,d.client_id,d.site_name,d.billing_mode,d.trip_date);if(!r){$('edit-status').textContent='No directory rule for this client/site/work date. Enter the rates manually.';return;}
    f.transport_rate.value=r.transport_rate;f.ot_rate.value=r.ot_rate??'';f.break_minutes.value=r.break_minutes;edit.snapshot={...r};$('edit-status').textContent='Applied directory rate effective '+r.effective_from;previewEdit();
  }
  function openTrip(row={},kind='new',index=null){let x=row;if(kind==='pending')x={...row.confirmed_data,driver_id:row.driver_id,driver:row.driver,provider_id:row.driver?.provider_id,source_image_url:row.source_image_url,source_image_key:row.source_image_key,source:'image_extract'};
    if(kind==='bulk')x={...row.extracted_data,client_id:SETUP.clients.find(r=>r.name.toLowerCase()===String(row.extracted_data?.client||'').toLowerCase())?.id||'',provider_id:SETUP.providers.find(r=>r.name.toLowerCase()===String(row.extracted_data?.transport_provider||'').toLowerCase())?.id||'',driver_id:SETUP.drivers.find(r=>r.name.toLowerCase()===String(row.extracted_data?.driver_name||'').toLowerCase())?.id||'',billing_mode:/trip/i.test(row.extracted_data?.work_type||'')?'trip':/night/i.test(row.extracted_data?.work_type||'')?'night':'day',source_image_key:row.image_key,source_image_url:row.image_url,source:'image_extract'};
    if(kind==='bulk-reviewed')kind='bulk';edit={kind,id:row.id,row:x,index,snapshot:x.rate_snapshot||{}};const mode=x.billing_mode||'day';$('edit-title').textContent=kind==='pending'?'Review Driver Submission':kind==='bulk'?'Review Uploaded Trip Sheet':kind==='new'?'Record Trip':'Edit Trip';$('save-edit').textContent=kind==='pending'?'Approve & Save':kind==='bulk'?'Confirm Review':'Save Trip';
    const modes=[{id:'day',name:'Day Work'},{id:'night',name:'Night Work'},{id:'trip',name:'Trip Basis'}];if(mode==='legacy')modes.push({id:'legacy',name:'Legacy record — keep original billing'});
    $('edit-fields').innerHTML=select('client_id','Client',SETUP.clients,x.client_id)+field('site_name','Site',x.site_name||'', 'text',true,'list="site-options" maxlength="160"')+`<datalist id="site-options">${[...new Set(RULES.map(r=>r.site_name))].map(s=>`<option value="${E(s)}">`).join('')}</datalist>`+select('provider_id','Provider',SETUP.providers,x.provider_id)+select('billing_mode','Work Type',modes,mode)+select('driver_id','Driver',SETUP.drivers,x.driver_id,false)+field('trip_date','Work Date',x.trip_date||(kind==='new'?new Date().toLocaleDateString('en-CA'):''),'date',true)+field('do_no','DO Number',x.do_no||'','text',true,'maxlength="80"')+field('truck_no','Truck Number',x.truck_no||'','text',true,'maxlength="40"')+field('trip_sheet_no','Sheet Reference (optional)',x.trip_sheet_no||'','text',false,'maxlength="80"')+field('pickup_location','Pickup (if shown)',x.pickup_location||'','text',false,'maxlength="240"')+field('delivery_location','Delivery (if shown)',x.delivery_location||'','text',false,'maxlength="240"')+field('start_time','Start Time',x.start_time?.slice(0,5)||'','time')+field('end_time','End Time',x.end_time?.slice(0,5)||'','time')+field('break_minutes','Lunch / Break Deduction (minutes)',x.break_minutes??(mode==='day'?60:0),'number',true,'min="0" max="720" step="1"')+field('quantity',mode==='legacy'?'Legacy Quantity':'Number of Trips',x.quantity||1,'number',true,mode==='legacy'?'min="0.001" step="0.001"':'min="1" step="1"')+field('transport_rate','Basic Hourly / Per Trip Rate (S$)',x.transport_rate??'','number',true,'min="0" step="0.01"')+field('ot_rate','OT Hourly Rate (S$)',x.ot_rate??'','number',false,'min="0" step="0.01"');
    $('edit-status').textContent='';if(kind==='pending')$('edit-status').textContent='Check the original sheet and rates before approval.';
    if(x.source_image_key){$('edit-status').innerHTML+='<p><button type="button" class="tt-btn ghost" id="open-source">Open Original Trip Sheet</button></p>';const sourceKind=kind==='pending'?'submission':kind==='bulk'?'import':'trip';$('open-source').onclick=()=>sourceDocument(sourceKind,row.id);}else if(x.source_image_url){const u=new URL(x.source_image_url,location.href);if(u.protocol==='https:')$('edit-status').innerHTML+='<p><a href="'+E(u.href)+'" target="_blank" rel="noopener noreferrer">Open original trip sheet</a></p>';}
    const f=$('edit-form').elements;for(const n of ['client_id','site_name','billing_mode','trip_date'])f[n].onchange=()=>{if(n==='billing_mode'){f.break_minutes.value=f.billing_mode.value==='day'?60:0;}applyRule();};
    f.driver_id.onchange=()=>{const d=SETUP.drivers.find(r=>r.id===f.driver_id.value);if(d?.truck_no&&!f.truck_no.value)f.truck_no.value=d.truck_no;if(d?.provider_id&&!f.provider_id.value)f.provider_id.value=d.provider_id;};
    $('edit-form').oninput=previewEdit;previewEdit();if(kind==='new'||kind==='bulk')applyRule();$('edit-dialog').showModal();
  }
  $('new-trip').onclick=()=>openTrip();$('close-edit').onclick=$('cancel-edit').onclick=()=>$('edit-dialog').close();$('apply-rule').onclick=applyRule;
  $('edit-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const data=editData();if(!data.work_type_id)return $('edit-status').textContent='Matching work type is missing from Master Data.';busy=true;$('save-edit').disabled=true;
    try{if(edit.kind==='bulk'){REVIEW[edit.index].reviewed=data;renderBulk();$('edit-dialog').close();return;}
      await api(edit.kind==='pending'?base+'/submissions/'+edit.id+'/approve':edit.kind==='edit'?base+'/trips/'+edit.id:base+'/trips',{method:edit.kind==='edit'?'PATCH':'POST',body:JSON.stringify(data)});
      MONTH=data.trip_date.slice(0,7);qa('.js-month').forEach(y=>y.value=MONTH);$('edit-dialog').close();await load();pane('register');
    }catch(err){$('edit-status').textContent=err.message;}finally{busy=false;$('save-edit').disabled=false;}
  };
  async function refreshMasters(){[SETUP,RULES]=await Promise.all([api(base+'/setup'),api(base+'/rate-rules')]);renderMasters();}
  function renderMasters(){for(const [key,id]of [['clients','master-clients'],['providers','master-providers'],['work_types','master-work-types']])$(id).innerHTML=SETUP[key].filter(r=>key!=='work_types'||/day|night|trip/i.test(r.name)).map(r=>`<span class="tt-chip">${E(key==='work_types'&&/trip/i.test(r.name)?'Trip Basis':r.name)}</span>`).join('');
    $('master-drivers').innerHTML=SETUP.drivers.map(r=>`<div><b>${E(r.name)}</b><br><small>${E(r.phone||'No phone')} · ${E(r.truck_no||'No truck')}</small>${SETUP.can_manage?`<div><button class="tt-btn small ghost" data-driver-edit="${E(r.id)}">Edit Driver</button><button class="tt-btn small ghost" data-link="${E(r.id)}">Generate / Replace Link</button><button class="tt-btn small danger" data-disable="${E(r.id)}">Disable Link</button></div><div data-link-result="${E(r.id)}"></div>`:''}</div>`).join('');
    $('rule-rows').innerHTML=RULES.map(r=>`<tr><td>${E(r.client?.name)}</td><td>${E(r.site_name)}</td><td>${E(names[r.billing_mode])}</td><td>${M(r.transport_rate)}</td><td>${r.ot_rate==null?'—':M(r.ot_rate)}</td><td>${r.break_minutes}</td><td>${E(r.effective_from)}</td><td>${SETUP.can_manage?`<button class="tt-btn small ghost" data-version="${E(r.id)}">New Version</button><button class="tt-btn small ghost" data-toggle="${E(r.id)}">${r.active?'Disable':'Enable'}</button>`:r.active?'Active':'Disabled'}</td></tr>`).join('')||'<tr><td colspan="8" class="tt-empty">Add your client/site rates before sharing driver links. No prices are assumed.</td></tr>';
    qa('.master-add').forEach(b=>{b.classList.toggle('tt-hidden',!SETUP.can_manage);b.onclick=()=>openMaster(b.dataset.kind);});$('add-rule').hidden=!SETUP.can_manage;$('common-link-tools').hidden=!SETUP.can_manage;$('master-note').classList.toggle('tt-hidden',SETUP.can_manage);
    qa('[data-driver-edit]').forEach(b=>b.onclick=()=>openMaster('drivers',SETUP.drivers.find(r=>r.id===b.dataset.driverEdit)));
    qa('[data-link]').forEach(b=>b.onclick=async()=>{if(!confirm('Generate a new private upload link? Any previous link for this driver will stop working.'))return;try{const res=await api(base+'/drivers/'+b.dataset.link+'/link',{method:'POST'}),url=new URL('driver-upload.html',location.href);url.hash=res.token;const driver=SETUP.drivers.find(r=>r.id===b.dataset.link),phone=String(driver.phone||'').replace(/\D/g,''),text='VCMS trip sheet upload for '+driver.name+': '+url.href;const box=document.querySelector('[data-link-result="'+b.dataset.link+'"]');box.innerHTML=`<p><input readonly aria-label="Driver upload link" value="${E(url.href)}"></p><button class="tt-btn small ghost" data-copy>Copy Link</button> <a class="tt-btn small green" href="https://wa.me/${phone}?text=${encodeURIComponent(text)}" target="_blank" rel="noopener noreferrer">Share to WhatsApp</a>`;box.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);box.querySelector('[data-copy]').textContent='Copied';}catch{box.querySelector('input').select();}};}catch(e){message(e.message);}});
    qa('[data-disable]').forEach(b=>b.onclick=async()=>{if(!confirm('Disable this driver upload link?'))return;try{await api(base+'/drivers/'+b.dataset.disable+'/link',{method:'DELETE'});message('Driver link disabled.');}catch(e){message(e.message);}});
    qa('[data-version]').forEach(b=>b.onclick=()=>openMaster('rule',RULES.find(r=>r.id===b.dataset.version)));
    qa('[data-toggle]').forEach(b=>b.onclick=async()=>{const r=RULES.find(r=>r.id===b.dataset.toggle);try{await api(base+'/rate-rules/'+r.id+'/active?active='+!r.active,{method:'PATCH'});await refreshMasters();}catch(e){message(e.message);}});
    const c=$('report-client').value,p=$('report-provider').value;$('report-client').innerHTML=options(SETUP.clients,c,'All clients');$('report-provider').innerHTML=options(SETUP.providers,p,'All providers');filterSites();
  }
  function openMaster(kind,r={}){masterKind=kind;masterID=kind==='drivers'?(r.id||null):null;$('master-title').textContent=kind==='rule'?'Client / Site Rate Rule':kind==='drivers'?'Register Driver':'Add '+kind;
    $('master-fields').innerHTML=kind==='rule'?select('client_id','Client',SETUP.clients,r.client_id)+field('site_name','Site',r.site_name||'','text',true,'maxlength="160"')+select('billing_mode','Work Type',[{id:'day',name:'Day Work'},{id:'night',name:'Night Work'},{id:'trip',name:'Trip Basis'}],r.billing_mode||'day')+field('transport_rate','Basic Hourly / Per Trip Rate',r.transport_rate??'','number',true,'min="0" step="0.01"')+field('ot_rate','OT Hourly Rate',r.ot_rate??'','number',true,'min="0" step="0.01"')+field('break_minutes','Break Deduction (minutes)',r.break_minutes??60,'number',true,'min="0" max="720" step="1"')+field('effective_from','Effective Work Date',new Date().toLocaleDateString('en-CA'),'date',true):field('name',kind==='drivers'?'Driver Full Name':'Name',r.name||'','text',true,'maxlength="160"')+(kind==='drivers'?field('phone','Phone with country code',r.phone||'','tel',true,'maxlength="30"')+field('truck_no','Truck Number',r.truck_no||'','text',false,'maxlength="40"')+select('provider_id','Provider',SETUP.providers,r.provider_id||'',false):'');
    if(kind==='rule'){$('master-form').elements.ot_rate.required=(r.billing_mode||'day')!=='trip';$('master-form').elements.billing_mode.onchange=()=>{const f=$('master-form').elements;f.break_minutes.value=f.billing_mode.value==='day'?60:0;f.ot_rate.required=f.billing_mode.value!=='trip';};}$('master-status').textContent='';$('master-dialog').showModal();
  }
  $('generate-common').onclick=async()=>{if(!confirm('Generate a common driver link? Any previous common link will stop working.'))return;try{const res=await api(base+'/portal-link',{method:'POST'}),url=new URL('driver-upload.html',location.href);url.hash=res.token;const box=$('common-link-result');box.innerHTML='<p><input readonly aria-label="Common driver upload link" value="'+E(url.href)+'"></p><button class="tt-btn small ghost" data-copy>Copy Common Link</button> <a class="tt-btn small green" target="_blank" rel="noopener noreferrer" href="https://wa.me/?text='+encodeURIComponent('VCMS trip sheet upload: '+url.href)+'">Share to WhatsApp</a>';box.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(url.href);box.querySelector('[data-copy]').textContent='Copied';}catch{box.querySelector('input').select();}};}catch(e){message(e.message);}};
  $('disable-common').onclick=async()=>{if(!confirm('Disable the common driver upload link?'))return;try{await api(base+'/portal-link',{method:'DELETE'});$('common-link-result').textContent='Common link disabled.';}catch(e){message(e.message);}};
  $('add-rule').onclick=()=>openMaster('rule');$('close-master').onclick=()=>$('master-dialog').close();
  $('master-form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{if(masterKind==='rule'){data.transport_rate=Number(data.transport_rate);data.ot_rate=data.ot_rate===''?null:Number(data.ot_rate);data.break_minutes=Number(data.break_minutes);await api(base+'/rate-rules',{method:'POST',body:JSON.stringify(data)});}else{if(!data.provider_id)data.provider_id=null;await api(masterID?base+'/drivers/'+masterID:base+'/masters/'+masterKind,{method:masterID?'PATCH':'POST',body:JSON.stringify(data)});}$('master-dialog').close();await refreshMasters();}catch(err){$('master-status').textContent=err.message;}};
  async function uploadPreview(blob,batch,name){if(typeof _vmmsEnsureFresh==='function')await _vmmsEnsureFresh();const r=await fetch(VMMS_CONFIG.BACKEND_URL+base+'/intake/preview',{method:'POST',headers:{Authorization:'Bearer '+getSession().access_token,'Content-Type':blob.type,'X-Batch-ID':batch,'X-File-Name':encodeURIComponent(name)},body:blob});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.detail||'File upload failed');return data;}
  async function processFiles(files){if(!files.length)return;if(files.length>30)return message('Select a maximum of 30 files per batch.');REVIEW=[];$('review-panel').classList.add('tt-hidden');$('bulk-progress-box').classList.remove('tt-hidden');$('file-list').innerHTML='';
    try{const batch=await api(base+'/import-batches',{method:'POST',body:JSON.stringify({total_files:files.length})});BATCH_ID=batch.id;for(let i=0;i<files.length;i++){const line=document.createElement('p');$('file-list').append(line);line.textContent=files[i].name+' — preparing';try{const prepared=await T.prepare(files[i]);if(prepared.warnings.length)throw Error(prepared.warnings.join(' '));line.textContent=files[i].name+' — uploading and reading';const item=await uploadPreview(prepared.blob,BATCH_ID,files[i].name);REVIEW.push(item);line.textContent=files[i].name+' — ready for review';}catch(err){line.textContent=files[i].name+' — '+err.message;}$('bulk-progress').style.width=Math.round((i+1)/files.length*100)+'%';$('bulk-status').textContent=(i+1)+' / '+files.length+' processed';}renderBulk();}catch(err){$('bulk-status').textContent=err.message;}finally{$('bulk-files').value='';}}
  function renderBulk(){$('review-panel').classList.toggle('tt-hidden',!REVIEW.length);$('review-rows').innerHTML=REVIEW.map((r,i)=>`<div class="tt-card tt-pad"><b>${E(r.original_name)}</b><p>${E([...(r.extracted_data?.warnings||[]),...(r.extracted_data?.quality_warnings||[])].join(' · '))}</p><button class="tt-btn ghost" data-review="${i}">${r.reviewed?'✓ Reviewed — Edit':'Review Details'}</button></div>`).join('');$('review-rows').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.review);if(REVIEW[i].reviewed)openTrip({...REVIEW[i].reviewed,id:REVIEW[i].id},'bulk-reviewed',i);else openTrip(REVIEW[i],'bulk',i);});}
  // A reviewed bulk row is still saved locally until Approve & Import All.
  $('bulk-files').onchange=e=>processFiles([...e.target.files]);const drop=$('drop-zone');drop.ondragover=e=>e.preventDefault();drop.ondrop=e=>{e.preventDefault();processFiles([...e.dataTransfer.files]);};
  $('commit-import').onclick=async()=>{if(REVIEW.some(r=>!r.reviewed))return $('bulk-status').textContent='Review and confirm each sheet before importing.';if(busy)return;busy=true;$('commit-import').disabled=true;try{const items=REVIEW.map(r=>({...r.reviewed,import_item_id:r.id}));await api(base+'/trips/bulk',{method:'POST',body:JSON.stringify({batch_id:BATCH_ID,items})});REVIEW=[];renderBulk();$('bulk-status').textContent='Trips approved and imported.';await load();pane('register');}catch(e){$('bulk-status').textContent=e.message;}finally{busy=false;$('commit-import').disabled=false;}};
  async function sourceDocument(kind,id){try{if(typeof _vmmsEnsureFresh==='function')await _vmmsEnsureFresh();const r=await fetch(VMMS_CONFIG.BACKEND_URL+base+'/documents/'+kind+'/'+id,{headers:{Authorization:'Bearer '+getSession().access_token},cache:'no-store'});if(!r.ok)throw Error('Original document could not be opened');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){$('edit-status').textContent=e.message;}}
  async function download(kind,filtered){const params=periodParams();params.set('work_type',$('work-filter').value);if(filtered){if($('report-client').value)params.set('client_id',$('report-client').value);if($('report-site').value)params.set('site_name',$('report-site').value);if($('report-provider').value)params.set('provider_id',$('report-provider').value);}
    message('Preparing export…');try{if(typeof _vmmsEnsureFresh==='function')await _vmmsEnsureFresh();const r=await fetch(VMMS_CONFIG.BACKEND_URL+base+'/export/'+kind+'?'+params,{headers:{Authorization:'Bearer '+getSession().access_token},cache:'no-store'});if(!r.ok){const data=await r.json();throw Error(data.detail||'Export failed');}const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='VCMS_Tipper_'+($('period-mode').value==='range'?$('date-from').value+'_to_'+$('date-to').value:MONTH)+'_'+kind+(kind==='xlsx'?'.xlsx':'.pdf');a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);message('');}catch(e){message(e.message);}}
  $('export-csv').onclick=()=>download('xlsx',false);$('register-pdf').onclick=()=>download('summary-pdf',false);$('report-csv').onclick=()=>download('xlsx',true);$('print-report').onclick=()=>download('summary-pdf',true);$('documents-pdf').onclick=()=>download('documents-pdf',true);
  (async()=>{try{await api('/api/v1/me');const now=new Date();MONTH=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');qa('.js-month').forEach(x=>x.value=MONTH);await refreshMasters();await load();}catch(e){message(e.message);}})();
})();
