(function(root,factory){
  var api=factory();
  if(typeof module==="object"&&module.exports)module.exports=api;
  else root.VcmsWbsTree=api;
})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
  function copy(nodes){return nodes.map(function(n){return Object.assign({},n)})}
  function ordered(nodes,parent){return nodes.filter(function(n){return(n.parent_id||null)===(parent||null)}).sort(function(a,b){return a.sort_order-b.sort_order||a.code.localeCompare(b.code)})}
  function normalize(input){var nodes=copy(input),seen={};function walk(parent,depth){if(depth>6)throw new Error("WBS hierarchy cannot exceed 6 levels");ordered(nodes,parent).forEach(function(n,i){if(seen[n.id])throw new Error("WBS hierarchy cannot contain a cycle");seen[n.id]=true;n.depth=depth;n.sort_order=(i+1)*1000;walk(n.id,depth+1)})}walk(null,1);if(Object.keys(seen).length!==nodes.length)throw new Error("WBS hierarchy contains an invalid parent or cycle");return nodes}
  function result(nodes,changed,error){return{nodes:nodes,changed:changed,error:error||null}}
  function move(input,id,direction){var nodes=copy(input),node=nodes.find(function(n){return n.id===id});if(!node)return result(input,false,"WBS node not found");var siblings=ordered(nodes,node.parent_id),at=siblings.findIndex(function(n){return n.id===id}),to=at+direction;if(to<0||to>=siblings.length)return result(input,false,direction<0?"Already first":"Already last");var other=siblings[to],tmp=node.sort_order;node.sort_order=other.sort_order;other.sort_order=tmp;return result(normalize(nodes),true)}
  function indent(input,id){var nodes=copy(input),node=nodes.find(function(n){return n.id===id});if(!node)return result(input,false,"WBS node not found");var siblings=ordered(nodes,node.parent_id),at=siblings.findIndex(function(n){return n.id===id});if(at<1)return result(input,false,"A preceding WBS node is required to indent");var parent=siblings[at-1],children=ordered(nodes,parent.id);node.parent_id=parent.id;node.sort_order=children.length?children[children.length-1].sort_order+1000:1000;try{return result(normalize(nodes),true)}catch(e){return result(input,false,e.message)}}
  function outdent(input,id){var nodes=copy(input),node=nodes.find(function(n){return n.id===id});if(!node)return result(input,false,"WBS node not found");if(!node.parent_id)return result(input,false,"Already at the top level");var parent=nodes.find(function(n){return n.id===node.parent_id});if(!parent)return result(input,false,"WBS parent not found");node.parent_id=parent.parent_id||null;node.sort_order=parent.sort_order+500;try{return result(normalize(nodes),true)}catch(e){return result(input,false,e.message)}}
  return{normalize:normalize,moveUp:function(n,id){return move(n,id,-1)},moveDown:function(n,id){return move(n,id,1)},indent:indent,outdent:outdent};
});
