const {test,expect}=require('@playwright/test');
const LM='20000000-0000-0000-0000-000000000001',LG='40000000-0000-0000-0000-000000000001',ITEM='50000000-0000-0000-0000-000000000001';
const DOC='30000000-0000-0000-0000-000000000001',CHART='30000000-0000-0000-0000-000000000002',GDOC='30000000-0000-0000-0000-000000000003';
function fixture(manage=true){return {can_manage:manage,machines:[{id:LM,machine_id:'LC1',vehicle_number:'XE1807Y',lm_number:'LM563989N',equipment:'Palfinger PK53002 SH',swl_kg:10400,certificate_expiry:'2027-05-27',examination_date:'2026-05-28',validity_6:'2026-11-27',validity_12:'2027-05-27',status:'Valid',current_document_id:DOC}],gear_certificates:[{id:LG,lg_number:'LG2511S023-024',gear_type:'Webbing sling',size:'3 inch',length:'6 m',swl_kg:3000,examination_date:'2026-01-01',certificate_expiry:'2027-01-01',next_renewal:'2026-12-31',status:'Valid',current_document_id:GDOC}],gear_items:[{id:ITEM,certificate_id:LG,marking:'S023',current_machine_id:LM,condition:'available'}],documents:[{id:DOC,kind:'lm',original_filename:'LM563989N.pdf',machine_id:LM,verified:true,created_at:'2026-09-30'},{id:CHART,kind:'load_chart',original_filename:'Load chart.pdf',machine_id:LM,verified:true,created_at:'2026-09-30'},{id:GDOC,kind:'lg',original_filename:'Two slings.pdf',gear_certificate_id:LG,verified:true,created_at:'2026-09-30'}],movements:[],packs:[]}}
async function boot(page,manage=true){let data=fixture(manage),writes=[];await page.addInitScript(()=>localStorage.setItem('vmms_session',JSON.stringify({access_token:'test',refresh_token:'test',expires_at:Date.now()+3600000})));await page.route('**/api/v1/**',async route=>{let req=route.request(),url=new URL(req.url());if(req.method()==='POST'){writes.push({url:url.pathname,body:req.postDataJSON()});if(url.pathname.endsWith('/packs'))return route.fulfill({json:{id:'pack1'}});if(url.pathname.endsWith('/move')){data.gear_items[0].current_machine_id=null;return route.fulfill({json:{id:'movement1'}})}return route.fulfill({json:{id:'new-document'}})}if(url.pathname.endsWith('/pdf'))return route.fulfill({contentType:'application/pdf',body:'%PDF-1.4 test'});if(url.pathname==='/api/v1/me')return route.fulfill({json:{role:manage?'admin':'site_sup',name:'QA User',user_id:'qa'}});if(url.pathname==='/api/v1/lifting')return route.fulfill({json:data});return route.fulfill({json:[]})});await page.goto('/lifting.html');await expect(page.locator('#notice')).toContainText(manage?'Records saved securely':'View access');return {writes,data}}

test('landing list, four sections and mobile layout preserve readable actions',async({page,isMobile})=>{await boot(page);await expect(page.locator('#machine-list')).toContainText('XE1807Y');if(!isMobile){await expect(page.locator('body')).toHaveClass(/vcms-shelled/);await expect.poll(()=>page.locator('.lift-main').evaluate(el=>el.getBoundingClientRect().left)).toBeGreaterThanOrEqual(236)} await page.screenshot({animations:'disabled',path:require('path').join(process.env.LIFTING_SCREENSHOT_DIR||require('os').tmpdir(),isMobile?'lifting-mobile.png':'lifting-desktop.png'),fullPage:true});await expect(page.locator('#summary')).toContainText('Total machines');await expect(page.locator('#attention')).toContainText('No outstanding');if(isMobile){await expect(page.locator('#section')).toBeVisible();await expect(page.locator('.lift-tabs')).toBeHidden();await expect(page.locator('#machine-list .lift-mobile-cards')).toBeVisible();await page.locator('#section').selectOption('lg')}else{await page.getByRole('button',{name:'LG Log',exact:true}).click()}await expect(page.locator('#lg')).toBeVisible();await expect(page.locator('#lg-list')).toContainText('LC1 · S023');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();await page.reload();await expect(page.locator('#lg')).toBeVisible()});

test('machine details start a pack with current holder and editable original order',async({page,isMobile})=>{let {writes}=await boot(page);let layout=isMobile?'.lift-mobile-cards':'.lift-table-wrap';await page.locator('#machine-list '+layout).getByRole('button',{name:'Details',exact:true}).click();await expect(page.locator('#detail-body')).toContainText('S023');await page.getByRole('button',{name:'Generate Client Document Pack'}).click();await expect(page.locator('#pack')).toBeVisible();await expect(page.locator('#pack-order')).toContainText('LM563989N.pdf');await page.getByLabel('Move document down',{exact:true}).first().click();await page.getByLabel('Include Load chart.pdf').uncheck();await page.locator('#pack-ack').check();await page.getByRole('button',{name:'Generate PDF pack',exact:true}).click();await expect.poll(()=>writes.length).toBe(1);let b=writes[0].body;expect(b.machine_id).toBe(LM);expect(b.item_ids).toEqual([ITEM]);expect(b.document_ids).not.toContain(CHART);expect(b.order[0]).toBe('lg_log');expect(b.acknowledge_warnings).toBeTruthy()});

test('movement records expected holder and refreshes assignment',async({page,isMobile})=>{let {writes}=await boot(page);if(isMobile)await page.locator('#section').selectOption('lg');else await page.getByRole('button',{name:'LG Log',exact:true}).click();let layout=isMobile?'.lift-mobile-cards':'.lift-table-wrap';await page.locator('#lg-list '+layout).getByRole('button',{name:'Issue / Borrow / Return'}).click();await expect(page.locator('#move-context')).toContainText('Currently with LC1');await page.locator('[name=issued_by]').fill('Issuer');await page.locator('[name=received_by]').fill('Receiver');await page.getByRole('button',{name:'Record movement',exact:true}).click();await expect(page.locator('#move-dialog')).not.toBeVisible();expect(writes[0].body.from_machine_id).toBe(LM);expect(writes[0].body.to_machine_id).toBeNull();await expect(page.locator('#lg-list')).toContainText('Store · S023')});

test('view role has no upload or movement actions',async({page,isMobile})=>{await boot(page,false);await expect(page.locator('#upload')).toBeHidden();if(isMobile)await page.locator('#section').selectOption('lg');else await page.getByRole('button',{name:'LG Log',exact:true}).click();await expect(page.getByRole('button',{name:'Issue / Borrow / Return'})).toHaveCount(0)});

test('LM review shows serial and manufacture year with full width source text',async({page,isMobile})=>{
 await boot(page);await page.route('**/api/v1/lifting/extract',route=>route.fulfill({json:{fields:{serial_number:'100330784',year_of_manufacture:2016},warnings:['Review every value against the original.']}}));
 await page.evaluate(()=>{window.pdfjsLib={GlobalWorkerOptions:{},getDocument:()=>({promise:Promise.resolve({numPages:1,getPage:async()=>({getTextContent:async()=>({items:[{str:'DISTINCTIVE NO. 2 100330784 YEAR OF MFG 2016'}]})}),destroy:async()=>{}})})}});
 await page.getByRole('button',{name:'Upload document',exact:true}).click();await page.locator('#file').setInputFiles({name:'qa-certificate.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 QA')});
 await expect(page.getByLabel('Distinctive / serial number',{exact:true})).toHaveValue('100330784');await expect(page.getByLabel('Year of Mfg',{exact:true})).toHaveValue('2016');
 await page.getByText('Extracted source text',{exact:true}).click();let widths=await page.locator('#extracted-source').evaluate(el=>({source:el.getBoundingClientRect().width,parent:el.parentElement.getBoundingClientRect().width}));expect(widths.source).toBeGreaterThan(widths.parent-2);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBeTruthy();
 await page.screenshot({animations:'disabled',path:require('path').join(process.env.LIFTING_SCREENSHOT_DIR||require('os').tmpdir(),isMobile?'lifting-review-mobile.png':'lifting-review-desktop.png'),fullPage:true});
 let upload;
 await page.route('**/api/v1/lifting/documents?*',async route=>{
   let req=route.request();upload={type:req.headers()['content-type'],bytes:req.postDataBuffer()};
   if(upload.type!=='application/pdf')return route.fulfill({status:415,json:{detail:'Use a valid PDF, JPG or PNG'}});
   return route.fulfill({status:201,json:{id:DOC}});
 });
 await page.getByLabel('Machine ID (enter manually)',{exact:true}).fill('LC-001');
 await page.locator('[name=confirmed]').check();await page.getByRole('button',{name:'Confirm and save',exact:true}).click();
 await expect(page.locator('#review-dialog')).not.toBeVisible();
 expect(upload.type).toBe('application/pdf');expect(upload.bytes.toString()).toBe('%PDF-1.4 QA');
 await expect(page.locator('#notice')).toContainText('Certificate reviewed and saved');
});
